select * from a_dw_jobs
where lower(employer_name1) like '%suisse%';

select * from a_dw_jobs
where lower(employer_name1) like '%amsouth%';

select * from a_dw_jobs
where lower(employer_name1) like '%bear%';

select * from a_dw_jobs
where lower(employer_name1) like '%stearns%';

select * from a_dw_jobs
where lower(employer_name1) like '%boston%';

select * from a_dw_jobs
where lower(employer_name1) like '%deutsche%';

select * from a_dw_jobs
where lower(employer_name1) like '%sachs%';

select * from a_dw_jobs
where lower(employer_name1) like '%morgan%';

select * from a_dw_jobs
where lower(employer_name1) like '%lynch%';

select * from a_dw_jobs
where lower(employer_name1) like '%societe%';

select * from a_dw_jobs
where lower(employer_name1) like '%solomon%';

select * from a_dw_jobs
where lower(employer_name1) like '%ubs%';

select * from a_dw_jobs
where lower(employer_name1) like '%bancorp%';
