/*******************************************/
/*******************************************/
/*** Disables All Triggers Before Import ***/
/*******************************************/
/*******************************************/
SPOOL d:\imports_exports\log_backup_import_tables\_triggers_disable.log;

/*** Random thought ... couldn't I just UPDATE user_constraints SET status='DISABLED" where constraint_type='R';   ?? ***/
/*** 01-15-2008 ***/


/*** Need to Disable/Enable Foreign Key Constraints Before Truncating All ***/
ALTER TABLE ADVANCE.DONOR_TOTALS DISABLE CONSTRAINT DONOR_TOTALS_FK1
/
ALTER TABLE ADVANCE.EP_ZL_COLUMN DISABLE CONSTRAINT EP_FK_ZL_TABLE_COLUMN
/
ALTER TABLE ADVANCE.EP_ZL_FROM DISABLE CONSTRAINT EP_FK_ZL_SELECT_FROM
/
ALTER TABLE ADVANCE.EP_ZL_FROM DISABLE CONSTRAINT EP_FK_ZL_TABLE_FROM
/
ALTER TABLE ADVANCE.EP_ZL_JOIN DISABLE CONSTRAINT EP_FK_ZL_COLUMN_JOIN
/
ALTER TABLE ADVANCE.EP_ZL_JOIN DISABLE CONSTRAINT EP_FK_ZL_COLUMN_JOIN_2
/
ALTER TABLE ADVANCE.EP_ZL_JOIN DISABLE CONSTRAINT EP_FK_ZL_SELECT_JOIN
/
ALTER TABLE ADVANCE.EP_ZL_JOIN_REPLACEMENT DISABLE CONSTRAINT EP_FK_ZL_JOIN_JOIN_REPLACE_FRO
/
ALTER TABLE ADVANCE.EP_ZL_JOIN_REPLACEMENT DISABLE CONSTRAINT EP_FK_ZL_JOIN_JOIN_REPLACE_TO
/
ALTER TABLE ADVANCE.EP_ZL_JOIN_REPLACEMENT DISABLE CONSTRAINT EP_FK_ZL_OUT_JOIN_REPLACE
/
ALTER TABLE ADVANCE.EP_ZL_JOIN_REPLACEMENT DISABLE CONSTRAINT EP_ZL_OUT_JOIN_REPLACE_ACT
/
ALTER TABLE ADVANCE.EP_ZL_JOIN_REPLACEMENT_SELECT DISABLE CONSTRAINT EP_FK_ZL_JOIN_REPLACE_SEL_J
/
ALTER TABLE ADVANCE.EP_ZL_JOIN_REPLACEMENT_SELECT DISABLE CONSTRAINT EP_FK_ZL_JOIN_REPLACE_SEL_JR
/
ALTER TABLE ADVANCE.EP_ZL_JOIN_REPLACEMENT_SELECT DISABLE CONSTRAINT EP_FK_ZL_JOIN_REPLACE_SEL_PS
/
ALTER TABLE ADVANCE.EP_ZL_JOIN_REPLACEMENT_SELECT DISABLE CONSTRAINT EP_ZL_JOIN_REPLACE_SEL_AS
/
ALTER TABLE ADVANCE.EP_ZL_OUTPUT_TYPE DISABLE CONSTRAINT EP_ZL_SELECT_OUTPUT_TYPE
/
ALTER TABLE ADVANCE.EP_ZL_OUTPUT_TYPE_SELECT DISABLE CONSTRAINT EP_FK_ZL_OUTPUT_TYPE_SELECT
/
ALTER TABLE ADVANCE.EP_ZL_OUTPUT_TYPE_SELECT DISABLE CONSTRAINT EP_FK_ZL_SELECT_OUT_TYPE_SELEC
/
ALTER TABLE ADVANCE.EP_ZL_RESULT_SET DISABLE CONSTRAINT EP_FK_ZL_COLUMN_RESULT_SET
/
ALTER TABLE ADVANCE.EP_ZL_RESULT_SET DISABLE CONSTRAINT EP_FK_ZL_SELECT_RESULT_SET
/
ALTER TABLE ADVANCE.EP_ZL_RESULT_SET_REPLACEMENT DISABLE CONSTRAINT EP_FK_ZL_OUTPUT_TYPE_REPLACE
/
ALTER TABLE ADVANCE.EP_ZL_RESULT_SET_REPLACEMENT DISABLE CONSTRAINT EP_FK_ZL_RESULT_REPLACE_FROM
/
ALTER TABLE ADVANCE.EP_ZL_RESULT_SET_REPLACEMENT DISABLE CONSTRAINT EP_FK_ZL_RESULT_REPLACE_TO
/
ALTER TABLE ADVANCE.EP_ZL_RESULT_SET_REPLACEMENT DISABLE CONSTRAINT EP_ZL_OUTPUT_TYPE_REPLACE_ACT
/
ALTER TABLE ADVANCE.EP_ZL_SELECT_RESTRICTION DISABLE CONSTRAINT EP_FK_ZL_SELECT_SELECT_REST
/
ALTER TABLE ADVANCE.EP_ZL_SELECT_RESTRICTION DISABLE CONSTRAINT EP_FK_ZL_SELECT_SELECT_REST2
/
ALTER TABLE ADVANCE.EP_ZL_SELECT_RESTRICTION DISABLE CONSTRAINT EP_FK_ZL_SEL_ZL_OUT_TYPE
/
ALTER TABLE ADVANCE.EP_ZL_SELECT_UNION DISABLE CONSTRAINT EP_FK_ZL_SELECT_SELECT_UNION
/
ALTER TABLE ADVANCE.EP_ZL_SELECT_UNION DISABLE CONSTRAINT EP_FK_ZL_SELECT_SELECT_UNION2
/
ALTER TABLE ADVANCE.WWW_PAGE_COMPONENT DISABLE CONSTRAINT FK_WWW_PAGE_COMPONENT_WWW_COMP
/
ALTER TABLE ADVANCE.WWW_PAGE_COMPONENT DISABLE CONSTRAINT FK_WWW_PAGE_PAGE_COMP_WWW_PAGE
/
ALTER TABLE ADVANCE.ZZ_DT_CL_CODE DISABLE CONSTRAINT ZZ_DT_CODE_FK1
/
ALTER TABLE ADVANCE.ZZ_DT_COL DISABLE CONSTRAINT ZZ_DT_COL_FK2
/
ALTER TABLE ADVANCE.ZZ_DT_COL DISABLE CONSTRAINT ZZ_DT_COL_FK3
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK1
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK2
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK3
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK4
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK5
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK6
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK7
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK8
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK9
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK10
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK11
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK12
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK13
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK14
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK15
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK16
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER DISABLE CONSTRAINT ZZ_DT_HEADER_FK17
/
ALTER TABLE ADVANCE.ZZ_DT_HEADER_COL DISABLE CONSTRAINT ZZ_DT_HEADER_COL_FK1
/
ALTER TABLE ADVANCE.WWW_COMPONENT DISABLE CONSTRAINT CKC_ACTIVE_IND_WWW_COMP
/
ALTER TABLE ADVANCE.WWW_DW DISABLE CONSTRAINT CKC_ACTIVE_IND_WWW_DW
/
ALTER TABLE ADVANCE.WWW_PAGE DISABLE CONSTRAINT CKC_ACTIVE_IND_WWW_PAGE
/
ALTER TABLE ADVANCE.WWW_PAGE DISABLE CONSTRAINT CKC_LOGON_REQ_IND_WWW_PAGE
/
/*** Disable/Enable Triggers ***/

ALTER TRIGGER ADVANCE.t_appeals DISABLE;

ALTER TRIGGER ADVANCE.t_memb_appeals DISABLE;

ALTER TRIGGER ADVANCE.t_name DISABLE;

COMMIT;
/

EXIT;