/*** Add a few fields ***/
drop table a_temp_heidi_stuff;
commit;

create table a_temp_heidi_stuff
(cwid varchar2(8),
name varchar2(40),
program varchar2(22),
degree varchar2(5),
major varchar2(5));
commit;

INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10313914', 'Al-Abbas, Mana M.', 'ME-MT-NT', 'ME', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10197352', 'Al-Ajmi, Nab M.', 'PHD-PE', 'PHD', 'PE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10314116', 'Al-Mostaneer, Hamad H.', 'PHD-ML', 'PHD', 'ML' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10437072', 'Albin, Jamie M.', 'MS-ML-NT', 'MS', 'ML' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10504173', 'Alexandre, Chloe S.', 'MS-GEOL', 'MS', 'GEOL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10314026', 'Alsughayyir, Mohammed', 'ME-MT-NT', 'ME', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10473383', 'Ambarak, Ahmed A.', 'PHD-EGEE11', 'PHD', 'EGEL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10473660', 'Ashames, Akram A.', 'MS-ML-NT', 'MS', 'ML' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10441804', 'Bajvani Gavanluei, Arshad', 'PHD-MT', 'PHD', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10292258', 'Baker, Darick J.', 'PHD-PHAP', 'PHD', 'APD' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10539038', 'Ball, David J.', 'MS-ES11-NT', 'MS', 'ES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10509678', 'Bearup, Lindsay A.', 'MS-ESHY11', 'MS', 'HY' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10504226', 'Becker, William L.', 'MS-EGME11', 'MS', 'EGMC' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10057415', 'Brown, Tyson W.', 'MS-MT', 'MS', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10441835', 'Chisholm, Joseph S.', 'MS-ESEX11-NT', 'MS', 'ES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10436655', 'Christensen, Kaneen E.', 'PHD-ES11', 'PHD', 'ES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10502010', 'Clark, Kevin A.', 'MS-EGEE11-NT', 'MS', 'EGEL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10470908', 'Cullenbine, Christopher A.', 'PHD-ME-OR', 'PHD', 'ME' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10243441', 'Dean, Arianne M.', 'MS-GEHY', 'MS', 'HY' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10505620', 'Dechongkit, Piya', 'MS-PE', 'MS', 'PE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10510973', 'Defilippo, Makko A.', 'MS-MT', 'MS', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10503253', 'Derrien, Richard', 'MS-MT', 'MS', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10012204', 'Edwards, Sarah A.', 'MS-GEOL', 'MS', 'GEOL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10267485', 'Faino, Nicolaus S.', 'MS-EGME11', 'MS', 'EGMC' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10060281', 'Farwell, Christopher L.', 'MS-PHNU-NT', 'MS', 'NU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10503254', 'Feng, Jufang', 'MS-GEOL', 'MS', 'GEOL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10280782', 'Forssen, Anna V.', 'MS-MATH', 'MS', 'MAGR' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10291030', 'Garza-Cruz, Tryana V.', 'PHD-EGMC', 'PHD', 'EGES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10503962', 'Gawai, Trupti D.', 'MS-CR11-NT', 'MS', 'CRE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10099892', 'Gibbs, Meghan J.', 'MS-MT', 'MS', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10275525', 'Glick, Joseph A.', 'MS-PHAP', 'MS', 'AP' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10291693', 'Goldberg, Judd', 'MS-GEOL', 'MS', 'GEOL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10402826', 'Gordon, Scott A.', 'MS-MT', 'MS', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10424526', 'Grabowski, David J.', 'MS-CR11-NT', 'MS', 'CRE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10307737', 'Horton, Titus C.', 'MS-EGME11-NT', 'MS', 'EGMC' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10039837', 'Howell, Andrew G.', 'PHD-CHAC', 'PHD', 'AC' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10039814', 'Jain, Luke A.', 'PHD-ML', 'PHD', 'ML' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10469531', 'Kiriluk, Kristin G.', 'PHD-PHAP', 'PHD', 'APD' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10437302', 'Kirschbaum, Michael J.', 'MS-GEOL', 'MS', 'GEOL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10314390', 'Lesher, Emily K.', 'PHD-ES11', 'PHD', 'ES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10538204', 'Liu, Junbiao', 'ME-PE-NT', 'ME', 'PE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10504200', 'Liu, Hui', 'MS-MATH', 'MS', 'MAGR' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10437485', 'Marchiori, Alan M.', 'PHD-MATH', 'PHD', 'MAGR' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10504782', 'Mehtiyev, Nijat', 'MS-PE', 'MS', 'PE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10276085', 'Mieritz, Emily A.', 'MS-ML-NT', 'MS', 'ML' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10403643', 'Nagle, Ashley A.', 'MS-EBTM-NT', 'MS', 'ETM' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10510952', 'Nekhorosheva, Vasilisa V.', 'MS-GEOL', 'MS', 'GEOL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10438544', 'Nowill, Courtney A.', 'PHD-MT', 'PHD', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10088024', 'Oyola, Lindsay A.', 'MS-EBME-NT', 'MS', 'MEE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10057327', 'Petri, Elliott B.', 'MS-ES11-NT', 'MS', 'ES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10472939', 'Protti, Bruno', 'MS-GEGN', 'MS', 'GEGN' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10439750', 'Reyes Hernandez, Tatiana', 'PHD-MT', 'PHD', 'MT' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10312260', 'Rietz, Roy K.', 'MS-EGEE11-NT', 'MS', 'EGEL' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10471262', 'Rose, Jason G.', 'MS-ESEX11-NT', 'MS', 'ES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10280397', 'Schneiderwind, Joseph D.', 'MS-MATH', 'MS', 'MAGR' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10473391', 'Shahid, Sidra', 'MS-GPYS', 'MS', 'GPYS' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10504360', 'Simmons, Leigh D.', 'MS-ESHY11', 'MS', 'HY' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10278454', 'Smith, Kristin M.', 'MS-EGME11-NT', 'MS', 'EGMC' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10279236', 'Somrit, Chotipong', 'PHD-MNES', 'PHD', 'MNES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10312174', 'Strain, Robert A.', 'MS-EBTM-NT', 'MS', 'ETM' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10504529', 'Sun, Changshun', 'MS-EGME11', 'MS', 'EGMC' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10503354', 'Swanson, Nathaniel R.', 'MS-GEEN', 'MS', 'GEGN' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10536662', 'Thompson, Michael V.', 'MS-EBME-NT', 'MS', 'MEE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10100768', 'Van Susante, Paulus J.', 'PHD-EGES', 'PHD', 'EGES' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10437915', 'Vasquez Cordano, Arturo L.', 'PHD-EBME', 'PHD', 'MEE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10282889', 'Walsh, Chris R.', 'MS-MATH', 'MS', 'MATH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10290376', 'Walthall, Rebecca M.', 'MS-EGCI11', 'MS', 'EGCV' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10292384', 'White, Eric A.', 'PHD-CR11', 'PHD', 'CRE' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_STUFF ( A_TEMP_HEIDI_STUFF.CWID, A_TEMP_HEIDI_STUFF.NAME, A_TEMP_HEIDI_STUFF.PROGRAM, A_TEMP_HEIDI_STUFF.DEGREE, A_TEMP_HEIDI_STUFF.MAJOR ) 
		 VALUES ( '10069934', 'Zabrusky, Kelsey J.', 'MS-GEOL', 'MS', 'GEOL' ) 
/

COMMIT;

alter table A_TEMP_HEIDI_STUFF
add id_number varchar2(10);

alter table A_TEMP_HEIDI_STUFF
add p_email_address varchar2(40);

alter table A_TEMP_HEIDI_STUFF
add imods_username varchar2(22);
commit;

update A_TEMP_HEIDI_STUFF t
   set t.id_number = 
    (select i.id_number
       from ids i
      where i.other_id = t.cwid
        and i.ids_type_code = 'CID');
        
update A_TEMP_HEIDI_STUFF t
   set t.p_email_address =
    (select dw.p_email_address
       from a_dw_address_good  dw
      where dw.id_number = t.id_number);
commit;   

update A_TEMP_HEIDI_STUFF t
set t.imods_username =
    (select t2.username
        from a_temp_imods_usernames  t2
       where t.id_number = t2.id_number);
commit;

update A_TEMP_HEIDI_STUFF t
     set t.id_number = ltrim(t.id_number,'0');
commit;   

--      select * from A_TEMP_HEIDI_STUFF
