drop table a_temp_heidi_grads;
/

create table a_temp_heidi_grads
(id varchar2(8),
 last_name varchar2(40),
 first_name varchar2(40),
 middle_name varchar2(40),
 email   varchar2(60),
 grad_date varchar2(80),
 status varchar2(2));
 commit;
 
 
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437713', 'Ahmedou Abouby', 'Mohameden', NULL, 'mahmedou@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10313914', 'Al-Abbas', 'Mana', 'Masleh', 'malabbas@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10197352', 'Al-Ajmi', 'Nab', 'M.', 'nalajmi@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10313481', 'Al-Hussain', 'Ahmad', 'Matoog', 'aalhussa@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436841', 'Al-Khars', 'Ghada', NULL, 'galkhars@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10314116', 'Al-Mostaneer', 'Hamad', 'Hussain', 'halmosta@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10440016', 'Al-Mulla', 'Abdullatif', 'Ebrahim Alhamer', 'abalmull@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10409109', 'Al-Nahdi', 'Rakan', 'Abdulhakim', 'ralnahdi@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10412697', 'Al-Shaibi', 'Muataz', 'Salem', 'malshaib@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437072', 'Albin', 'Jamie', 'Margaret', 'jalbin@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10504173', 'Alexandre', 'Chloe', 'Spencer', 'csalexan@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10472946', 'Allen', 'Stuart', 'Price', 'stallen@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10314026', 'Alsughayyir', 'Mohammed', NULL, 'malsugha@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10473383', 'Ambarak', 'Ahmed', 'Abdelsalam H.', 'aambarak@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435362', 'Amedo', 'Nicholas', 'D.', 'namedo@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10230669', 'Ammerman', 'Eryn', 'M.', 'eammerma@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10412421', 'Anderson', 'Matthew', 'T.', 'manderso@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436615', 'Anyak', 'Guot', 'Deng', 'ganyak@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10438561', 'Armstrong', 'Sean', 'Aaron', 'sarmstro@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10473660', 'Ashames', 'Akram', 'Ashour', 'aashames@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435655', 'Ashurst', 'Daniel', 'Josiah', 'dashurst@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10312653', 'Ast', 'Cory', 'R.', 'cast@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435590', 'Austin', 'Breanna', 'Cherise', 'baustin@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10438555', 'Bagley', 'Uzel', 'Malcolm', 'ubagley@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10441804', 'Bajvani Gavanluei', 'Arshad', NULL, 'abajvani@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10292258', 'Baker', 'Darick', 'Justin', 'dbaker@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10539038', 'Ball', 'David', 'Jacob', 'daball@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437513', 'Balogh', 'Elizabeth', 'Ashley', 'ebalogh@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10423816', 'Baseggio', 'Kyle', 'Timothy', 'kbaseggi@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436322', 'Bauer', 'Angela', 'R.', 'abauer@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436322', 'Bauer', 'Angela', 'R.', 'abauer@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10509678', 'Bearup', 'Lindsay', 'Ann', 'lpeters@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10504226', 'Becker', 'William', 'Labelle', 'wilbecke@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10040571', 'Boschert', 'Paul', 'T', NULL, '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10416790', 'Bravo', 'Joseph', 'Jarrett', 'jbravo@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10472651', 'Bristow', 'Brian', 'Patrick', 'bbristow@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10057415', 'Brown', 'Tyson', 'Whittier', 'tbrown@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10440344', 'Buhlaigah', 'Mustafa', 'Jamal', 'mbuhlaig@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10312781', 'Bulfer', 'Daniel', 'Richard', 'dbulfer@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10311911', 'Cabell-Kluch', 'Zachary', 'Nathanial', 'zcabellk@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10427105', 'Cannizzaro', 'Randall', 'James', 'rcannizz@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10506361', 'Chamorro Santillan', 'Lizeth', NULL, 'lchamorr@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10441835', 'Chisholm', 'Joseph', 'Sumner', NULL, '8/19/2016', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10410303', 'Chowdhry', 'Umair', 'Iqbal', 'uchowdhr@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436655', 'Christensen', 'Kaneen', 'Elizabeth', 'kachrist@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10502010', 'Clark', 'Kevin', 'Anthony', 'keclark@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10414161', 'Clavette', 'Alexander', 'Breant', 'aclavett@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436883', 'Conley', 'Benjamin', 'Michael', 'beconley@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435883', 'Craddock', 'Christopher', 'James', 'chcraddo@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10470908', 'Cullenbine', 'Christopher', 'Alan', 'ccullenb@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10413397', 'Cutt', 'Christopher', 'John', 'ccutt@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10414524', 'Dahlin', 'Matthew', 'Devro', 'mdahlin@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437283', 'DeKruif', 'Zachary', 'Daniel', 'zdekruif@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10243441', 'Dean', 'Arianne', 'M.', 'adean@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10505620', 'Dechongkit', 'Piya', NULL, 'pdechong@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10510973', 'Defilippo', 'Makko', 'Aaron', 'mdefilip@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10503253', 'Derrien', 'Richard', NULL, 'rderrien@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10270724', 'Dibble', 'John', 'Michael', 'jdibble@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436876', 'Dixon', 'Paul', 'William', 'pdixon@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10012204', 'Edwards', 'Sarah', 'Ann', 'sedwards@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10412457', 'Everist', 'Mathew', 'R.', 'meverist@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10267485', 'Faino', 'Nicolaus', 'S', 'nfaino@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10060281', 'Farwell', 'Christopher', 'Lien', 'cfarwell@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10503254', 'Feng', 'Jufang', NULL, 'jfeng@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10274852', 'Ferne', 'Russel', 'Lassen', 'rferne@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10413085', 'Fielding', 'Jacob', 'T.', 'jfieldin@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434304', 'Fitzsimons', 'Sean', 'Kornelly', 'sfitzsim@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10059756', 'Fletcher', 'Mark', 'Lee', 'mfletche@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10280782', 'Forssen', 'Anna', 'Victoria', 'aforssen@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10289227', 'Garcia', 'Amanda', 'Patricia', NULL, '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10291030', 'Garza-Cruz', 'Tryana', 'V.', 'tgarzacr@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10503962', 'Gawai', 'Trupti', 'Devendra', 'tgawai@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10441425', 'Gerber', 'Lydia', 'R.', 'lgerber@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10099892', 'Gibbs', 'Meghan', 'Jane', 'meryan@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10275525', 'Glick', 'Joseph', 'A.', 'jglick@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10440374', 'Goesch', 'Gary', 'James Link', 'ggoesch@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10291693', 'Goldberg', 'Judd', NULL, 'jgoldber@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10402826', 'Gordon', 'Scott', 'Allen', 'sgordon@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10424526', 'Grabowski', 'David', 'James', 'dgrabows@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10469859', 'Guercio', 'Dustin', 'Scott', 'dguercio@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437393', 'Gumieny', 'Keith', 'Alan', 'kgumieny@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436789', 'Gustin', 'Levi', 'Paul', 'lgustin@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10439008', 'Guynes', 'Jacob', 'Tyler', 'jguynes@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10309315', 'Hansen', 'Joshua', 'Lee', 'jhansen@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435539', 'Harmon', 'Zachary', 'Steven', 'zharmon@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10407400', 'Hasskamp', 'Adam', 'T.', 'ahasskam@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10305649', 'Hatch', 'Silas', 'Martin', 'shatch@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10433547', 'Heger', 'Tamara', 'Lynn', 'theger@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10080498', 'Hensel', 'Adam', 'Yoon Koo', 'ahensel@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10439315', 'Hill', 'Andrew', 'John', 'anhill@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10439315', 'Hill', 'Andrew', 'John', 'anhill@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10294237', 'Holmes', 'Nathaniel', 'Aaron', 'nholmes@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437682', 'Hornak', 'Julian', NULL, 'jhornak@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10307737', 'Horton', 'Titus', 'Craig', 'thorton@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10404371', 'Houlihan', 'Patrick', 'Michael', 'phouliha@mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10039837', 'Howell', 'Andrew', 'Grahl', 'ahowell@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10033990', 'Hubbard', 'Lex', 'Michael', 'lhubbard@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10312740', 'Hudson', 'Andrew', 'Sean', 'anhudson@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434316', 'Isherwood', 'Ryan', 'John', 'risherwo@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10039814', 'Jain', 'Luke', 'Anil', 'ljain@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10266260', 'Jones', 'Gregory', 'Murrel', 'gjones@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437807', 'Jukkola', 'Bryce', 'Aaron', 'bjukkola@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10406399', 'Kali', 'Davis', 'Anthony', 'dkali@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10414860', 'Kasberg', 'Michael', 'Joseph', 'mkasberg@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10309899', 'Keese', 'Cameron', 'R.', 'ckeese@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10422583', 'Kenfield', 'Marcus', 'Ryan', 'mkenfiel@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435228', 'Kenna', 'Meaghan', 'Elizabeth', 'mkenna@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10441388', 'Kilcrease', 'Kaily', 'Elaine', 'kkilcrea@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10251411', 'Kiley', 'Kristyn', 'Renae Barrows', NULL, '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10468931', 'Kirchhoff', 'Bryan', 'Dwayne', 'bkirchho@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436942', 'Kirchner', 'Aaron', 'Thomas', 'akirchne@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10469531', 'Kiriluk', 'Kristin', 'Gayle', 'kkiriluk@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437302', 'Kirschbaum', 'Michael', 'John', 'mkirschb@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10412115', 'Kopetzky', 'Cyndi', 'L.', 'ckopetzk@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434642', 'Kramer', 'Christopher', 'D.', 'chkramer@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10441410', 'Kumbera', 'Austin', 'Lawrence', 'akumbera@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437390', 'Lang', 'Scott', 'Alexander', 'slang@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10506320', 'Largent', 'Jacob', 'Wayne', 'jalargen@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10062273', 'Lease', 'Christopher', NULL, NULL, '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434584', 'Lee', 'Eric', 'Gaylen', 'elee@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10314390', 'Lesher', 'Emily', 'Katherine', 'elesher@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10402509', 'Li', 'Sharyn', NULL, 'xli@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10410468', 'Linck', 'Nicholas', 'W.', 'nlinck@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434682', 'Lindgren', 'Kurt', 'Alan', 'klindgre@mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10504200', 'Liu', 'Hui', NULL, 'huliu@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10538204', 'Liu', 'Junbiao', NULL, 'jliu@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10429681', 'Loew', 'Christopher', 'M.', 'cloew@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10429682', 'Loewen', 'Daniel', 'Paul', 'dloewen@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10313124', 'Lombardi', 'Kristine', 'Adele', 'klombard@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10414693', 'Long', 'Rhett', 'Carl', 'rlong@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10312515', 'Lousberg', 'Chad', 'Ryan', 'clousber@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10429782', 'Macdonald', 'Megan', 'Marie', 'mmacdona@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10290511', 'Magnusson', 'Candice', 'Elaine', 'cmagnuss@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437485', 'Marchiori', 'Alan', 'Michael', 'amarchio@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10413544', 'McClard', 'Katherine', 'E.', 'kmcclard@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10312531', 'McCollom', 'Brittany', 'Ann', 'bmccollo@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10411744', 'McConnell', 'Matthew', 'Cole', 'mmcconne@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10069625', 'McCullough', 'Robert', 'Alan', NULL, '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10411508', 'McKenna', 'Chad', 'Mattison', 'cmckenna@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434587', 'McManigal', 'Gregory', 'Scott', 'gmcmanig@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10429965', 'Mccarty-Daniels', 'Andrea', 'Jaclyn', 'amccarty@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10504782', 'Mehtiyev', 'Nijat', NULL, 'nmehtiye@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10276085', 'Mieritz', 'Emily', 'Anna', 'emieritz@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10301747', 'Mills', 'Zachary', 'Ert', 'zmills@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10079776', 'Mossman', 'James', 'Cole', 'jamossma@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10468389', 'Murphy', 'Mikaela', 'Rachelle', 'mimurphy@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10403643', 'Nagle', 'Ashley', 'Ann', 'anagle@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10510952', 'Nekhorosheva', 'Vasilisa', 'Valerievna', 'vnekhoro@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10438260', 'Nelson', 'Todd', 'Michael', 'tonelson@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10034433', 'Nieh', 'Hsiao-Po', NULL, 'hnieh@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10402300', 'Nocas', 'Noel', 'A.', 'nnocas@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10310172', 'Noelck', 'Jason', 'Walter', 'jnoelck@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10298010', 'Noland', 'Daniel', 'A.', 'dnoland@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10298010', 'Noland', 'Daniel', 'A.', 'dnoland@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10438544', 'Nowill', 'Courtney', 'Ann', 'cnowill@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10288002', 'Oczkus', 'Peter', 'Davis', 'poczkus@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10275989', 'Olagoke', 'Ezra', 'Oladele', 'ezolagok@mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435973', 'Olsen', 'Rory', 'Daniel Connor', 'rolsen@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437733', 'Ould Elmoctar-Salem', 'Cheikh', 'Elmoustapha', 'couldelm@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10088024', 'Oyola', 'Lindsay', 'Anne', 'lrothfel@mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10303326', 'Parten', 'Chelsea', 'Marie', 'cparten@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10403647', 'Patterson', 'Derek', 'L.', 'depatter@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10057327', 'Petri', 'Elliott', 'Burton', 'epetri@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10307792', 'Petrie', 'Paul', 'S.', 'ppetrie@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10429302', 'Phillips', 'Rachel', 'Hilary C.', 'rknuckle@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434068', 'Portman', 'Richard', 'Louis', 'rportman@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10472939', 'Protti', 'Bruno', NULL, 'bprotti@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10268918', 'Raber', 'Kevin', 'J.', 'kraber@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10268918', 'Raber', 'Kevin', 'J.', 'kraber@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10439750', 'Reyes Hernandez', 'Tatiana', NULL, 'treyeshe@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10312260', 'Rietz', 'Roy', 'Kenneth', 'rrietz@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10310281', 'Rodriguez', 'Mila', NULL, 'erodrigu@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10471262', 'Rose', 'Jason', 'Gerard', 'jgrose@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10280733', 'Rosenbach', 'Daniel', 'Benjamin', 'drosenba@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10406878', 'Roswold', 'Devin', 'J.', 'droswold@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436981', 'Runyan', 'Christopher', 'Evan', 'crunyan@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10404348', 'Rutter', 'Calvin', 'James', 'crutter@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10308850', 'Sadqi', 'Lahcen', NULL, 'lsadqi@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435205', 'Sale', 'Dustyn', 'Matthew', 'dsale@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10425755', 'Sandoval', 'Katelyn', 'E.', 'ksandova@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10412089', 'Schanel', 'Nicole', 'Marie', 'nschanel@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10410406', 'Schneider', 'Joseph', 'A.', 'joschnei@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10280397', 'Schneiderwind', 'Joseph', 'D.', 'jschneid@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10414521', 'Schulte', 'Grant', 'Michael', 'gschulte@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10056003', 'Schwartz', 'Nathan', 'Andrew', 'nschwart@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437734', 'Semlali', 'Mohamed', 'Melainine', 'msemlali@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10473391', 'Shahid', 'Sidra', NULL, NULL, '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437772', 'Sheets', 'Jamison', 'Kyle', 'jsheets@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10504360', 'Simmons', 'Leigh', 'Daniel', 'lesimmon@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10411369', 'Smith', 'Harrison', 'Scott', 'hasmith@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10278454', 'Smith', 'Kristin', 'M.', 'krismith@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10470521', 'Soiland', 'James', 'Vincent', 'jsoiland@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10279236', 'Somrit', 'Chotipong', NULL, 'csomrit@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10414848', 'Spadinger', 'William', 'Martin', 'wspading@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10421462', 'Stamp', 'Hilary', 'N.', 'hstamp@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436184', 'Steele', 'Jared', 'Russell', 'jasteele@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10496171', 'Stef', 'Ryan', 'John', 'rstef@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10300928', 'Stewart', 'Brandon', 'M', 'bstewart@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10296111', 'Straily', 'Ryan', 'Earl', 'rstraily@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10312174', 'Strain', 'Robert', 'Addison', 'rstrain@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10302934', 'Suchsland', 'Wesley', 'R.', 'wsuchsla@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10504529', 'Sun', 'Changshun', NULL, 'csun@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10307443', 'Svendsen', 'Thorn', 'C.', 'tsvendse@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10503354', 'Swanson', 'Nathaniel', 'Ray', 'nswanson@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434849', 'Sweenhart', 'Lance', 'A.', 'lsweenha@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10308732', 'Symonds', 'Adam', 'J.', 'asymonds@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436185', 'Taipale', 'Taylor', 'Mckinley', 'ttaipale@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10279962', 'Tanner', 'Benjamin', 'Carl', 'btanner@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436095', 'Thompson', 'Joshua', 'Paul', 'josthomp@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10536662', 'Thompson', 'Michael', 'Vincent Trevor', 'mithomps@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10435091', 'Tschacher', 'Anthony', 'Tyler', 'antschac@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10411176', 'Turlington', 'Peter', 'Fielding', 'pturling@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10100768', 'Van Susante', 'Paulus', 'Johannes', 'paulvans@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10456890', 'Vargo', 'Brandon', 'W.', 'bvargo@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437915', 'Vasquez Cordano', 'Arturo', 'Leonardo', 'avasquez@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10313939', 'Villa', 'Sergio', 'Rene', 'svilla@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434455', 'Walega', 'Erik', 'Andrew', 'ewalega@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10282889', 'Walsh', 'Chris', 'Ryan', 'cwalsh@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10290376', 'Walthall', 'Rebecca', 'Marilyn', 'rwalthal@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10406869', 'Watters', 'Aaron', 'James', 'awatters@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10471407', 'Welch', 'Britton', 'Davis', 'bwelch@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10407332', 'Westerhoff', 'Kimberly', 'Ann', 'kwesterh@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10292384', 'White', 'Eric', 'Andrew', 'ewhite@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10302807', 'Wilbur', 'Steven', 'David', 'swilbur@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10412548', 'Williams', 'Denver', 'Clayton', 'dewillia@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10437432', 'Woody', 'Evan', 'Frederick', 'ewoody@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434203', 'Woolman', 'Alexandra', 'Marie', 'awoolman@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436423', 'Wrisley', 'Craig', 'Everett', 'cwrisley@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10410028', 'Yadon', 'Alina', 'I.', 'ayadon@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10410028', 'Yadon', 'Alina', 'I.', 'ayadon@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10416603', 'Yahya', 'Sarah', 'Adil', 'sahmed@mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10434284', 'Yanowich', 'Laura', 'Noreen', 'lyanowic@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10442177', 'Yermekbayev', 'Rustem', 'Karimovich', 'ryermekb@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10436442', 'Young', 'Taylor', 'James', 'tyoung@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10069934', 'Zabrusky', 'Kelsey', 'Jo', 'kzabrusk@mymail.mines.edu', '12/16/2011', 'CH' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( '10433661', 'Zimmerman', 'Landan', 'N.', 'lzimmerm@mymail.mines.edu', '12/16/2011', 'AU' ) 
/
INSERT INTO ADVANCE.A_TEMP_HEIDI_GRADS ( A_TEMP_HEIDI_GRADS.ID, A_TEMP_HEIDI_GRADS.LAST_NAME, A_TEMP_HEIDI_GRADS.FIRST_NAME, A_TEMP_HEIDI_GRADS.MIDDLE_NAME, A_TEMP_HEIDI_GRADS.EMAIL, A_TEMP_HEIDI_GRADS.GRAD_DATE, A_TEMP_HEIDI_GRADS.STATUS ) 
		 VALUES ( NULL, NULL, NULL, NULL, NULL, NULL, NULL ) 
/

commit;

alter table A_TEMP_HEIDI_GRADS
add id_number varchar2(10);

update a_temp_heidi_grads h
   set h.id_number =
    (select i.id_number
       from ids  i
      where i.ids_type_code = 'CID'
        and i.other_id = h.id);
commit;
     
alter table a_temp_heidi_grads
add imods_username     varchar2(30);

update a_temp_heidi_grads t
   set t.imods_username =
        nvl((select u.username
           from a_temp_imods_usernames u
          where u.id_number = t.id_number),' ');
commit;          

--  select * from a_temp_heidi_grads