select *
from allocation
where lower(short_name) like '%hegglund%';

drop table a_temp_tbk;
commit;

create table a_temp_tbk
(fund varchar2(19),
aca varchar2(100),
banner varchar2(100),
fund_name varchar2(100));
commit;
--
-- TABLE INSERT STATEMENTS
--
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '24897', '', '624897', '' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30095', '0095', '42340', 'Hegglund Memorial Endowment Fu' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30097', '097', '62520', 'Sopris Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30100', '100', '62700', 'NREL Columbine Spirit Scholars' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30202', '202', '62640', 'Schlechten Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30204', '204', '48440', 'Mann Graduate Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30205', '205', '48510', 'Buell Fund/The Richard E.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30207', '207', '62180', 'Andrews Scholarship/Frank & Pe' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30208', '208', '62720', 'Yopps Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30216', '216', '33200', 'ARCO Humanities Program' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30242', '242', '62760', 'Stoddard Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30254', '254', '62800', 'Mattson Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30261', '261', '77380', 'Criley Memorial Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30267', '267', '47510', 'Borasio Award' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30282', '282', '62880', 'Frischknecht Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30294', '294', '62960', 'Garg Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30304', '304', '63040', 'Staritzky Scholarship/Eugene M' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30308', '308', '63080', 'Horvath Endowed Scholarship/Ch' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30309', '309', '63120', 'Waldschmidt Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30322', '322', '63160', 'Loeb Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30336', '336', '49670', 'Keck Foundation Teaching-Facul' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30338', '338', '63240', 'Keck Foundation Scholarship/W.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30339', '339', '48470', 'Stacy & Mike Visscher Memorial' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30346', '346', '60800', 'Davis Memorial Endowment/Pinky' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30349', '349', '63320', 'Sayre Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30357', '357', '47520', 'Philipose Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30366', '366', '20760', 'Cohen Family Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30367', '367', '36550', 'Kaanta Award/Henry W.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30372', '372', '62620', 'Combined Scholarship Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30377', '377', '49000', 'Donnelly Memorial/Alden S. & A' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30385', '385', '62340', 'Bolin Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30389', '389', '23520', 'ASARCO Endowment for ESEE' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30402', '402', '49630', 'Gates Teaching Equipment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30419', '419', '36560', 'ASARCO Endowment for Metallurg' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30421', '421', '63440', 'Gibson Scholarship/Robert L.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30428', '428', '63480', 'McCormack Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30437', '437', '49730', 'Gates Fdn. Environmental Devel' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30454', '454', '49020', 'Class of ''22' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30473', '473', '40120', 'Carlson Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30476', '476', '63520', 'Pauli Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30480', '', '60480', '' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30487', 'B487', '604878', 'Carlson Endowment for Exc. in Rugby' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30488', '488', '63600', 'Anderson Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30490', 'B490', '604906', 'Hiltrop Memorial Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30495', '495', '27440', 'Pan American Institute of Mini' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30497', 'B497', '604974', 'Thompson Memorial Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30502', 'B502', '6-05024', 'Heinze Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30503', '503', '49230', 'Library Acquisitions Geology' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30505', 'B505', '6-05058', 'Copper Club/Phelps Dodge Legacy Schl.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30509', 'B509', '0', 'Meissner Memorial Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30512', 'B512', '605127', 'James & Mary Jo Lake Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30514', 'B514', '', 'DeVoto Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30516', 'B516', '605169', 'Young Environmental Issues Symposium' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30517', 'B517', '', 'Family of Mines Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30521', 'B521', '605211', 'Thoma Pet. Eng. Merit Based Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30522', '522', '49040', 'Johnson Library/J. Harlan & Me' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30523', 'B523', '60523', 'Young Environmental Issues Symp. Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30533', '533', '77110', 'Tesone Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30538', '538', '31680', 'Hollister Student Award Geophy' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30540', '540', '49660', 'Keck Fdn. Distinguished Chair' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30545', '545', '49870', 'Cyprus Developmental Professor' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30553', '553', '49680', 'FIERF Developmental Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30569', '569', '49700', 'Moreno Endowed Professorship i' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30570', '570', '17280', 'Moreno Mineral Economic Facult' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30582', '582', '47570', 'Eisenhower Award (ROTC) Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30585', '585', '66540', 'Kline Memorial Fund/John V.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30597', '597', '40160', 'ASARCO Endowment/Mining Engin.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30598', '598', '63840', 'Martinez Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30600', '600', '49720', 'AMAX Chair in Environmental Sc' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30606', '606', '63880', 'Moore Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30608', '608', '49740', 'Moore Endowed Chair in Metallu' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30616', '616', '49760', 'Weaver Distng Professorship in' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30618', '618', '63920', 'Persse Scholarship/Franklin H.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30630', '630', '63960', 'Wilson Student Financial Aid' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30635', '635', '15280', 'Beckham Estate/Leland J.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30636', '636', '49570', 'Baxter Annuity/Robert A.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30639', '639', '40240', 'Washburn Award/Howard G.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30654', '654', '34880', 'Everett  Award in Math' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30655', '655', '49490', 'Dobelman Distinguished Chair i' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30658', '658', '49780', 'Brown Distinguished Chair in E' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30661', 'B661', '606617', 'Wallace Endowed Geology Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30662', 'B662', '606624', 'Wallace Endowed Undergrad Geology Schl.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30664', '664', '60180', 'Integral Club Alumni (I-CLUB)' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30665', '665', '36620', 'Cavanaugh Memorial Award/Charl' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30666', 'B666', '', 'Boettcher Fdtn. End. for Distinctive Ed.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30668', 'B668', '60668', 'Corbett Memorial Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30670', '670', '77160', 'Athletic Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30678', '678', '64120', 'Barry Scholarship/C. W.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30680', '680', '77200', 'Class of ''39 Athletic Scholars' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30683', '683', '49800', 'Paden Distinguished Chair in E' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30687', '687', '64140', 'Coors Jr. Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30688', '688', '64160', 'Linn Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30690', '690', '64200', 'Dumke Memorial Scholarship/Edn' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30693', '693', '64240', 'Hazen Financial Aid' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30695', '695', '64280', 'Hares Memorial Scholarship/Cha' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30696', '696', '64320', 'Johnston Memorial Scholarship/' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30697', '697', '64360', 'Bruce Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30699', '699', '64400', 'Lee Jr. Memorial Scholarship/J' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30700', '700', '64440', 'Parker Liddell Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30701', '701', '64480', 'Lindeman Jr. Memorial Scholars' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30702', '702', '64520', 'Chevron Academic Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30703', '703', '27500', 'Newhouser Geology Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30705', '705', '64420', 'Kuehl Scholarship Endowment Fu' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30706', '706', '64560', 'Murchison Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30708', '708', '64600', 'Parker & James Boyd Student De' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30709', '709', '64640', 'Paul Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30710', '710', '36570', 'Lake Metallurgy Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30711', '711', '64680', 'Rastall Scholarship/Ben M.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30713', '713', '27480', 'Caplan Endowed Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30715', '715', '64760', 'Mulryan Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30716', '716', '64800', 'Gulf Oil Foundation Endowed Sc' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30717', '717', '31690', 'Dunwoody Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30718', '718', '49710', 'The Davison Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30723', '723', '20860', 'Feldmiller Pub. Serv. Scholars' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30724', '724', '64840', 'Wickman Memorial Scholarship/C' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30726', '726', '64920', 'Gardner Memorial Scholarship/M' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30727', '727', '64960', 'Wells Fargo Minority Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30731', '731', '65080', 'Horne Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30732', '732', '17360', 'Risser Award-Mineral Ec/Hubert' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30734', '734', '65420', 'Obrecht ''34 Memorial Scholarsh' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30735', '735', '65160', 'Faculty Scholarship in Basic E' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30737', '737', '65200', 'Allardyce Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30739', '739', '11420', 'Selim Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30740', '740', '62580', 'Brewer Memorial Scholarship/Qu' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30741', '741', '65050', 'Siegert Endowed Fellowship Fun' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30742', '742', '77190', 'Swenson/N. A.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30744', '744', '65260', 'Brennecke Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30749', '749', '65270', 'DePuy Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30751', '751', '49100', 'Lake Endowment for Collections' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30753', '753', '65320', 'Weigand Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30757', '757', '65400', 'Harding Scholarship/Margaret &' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30762', '762', '77170', 'Athletic Endowed Scholarship F' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30764', '764', '65520', 'Felber Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30765', '765', '65560', 'Williams Companies Endowed Sch' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30774', '774', '77290', 'Marv Kay Athletics Department' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30777', '777', '27470', 'Van Tuyl Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30778', '778', '49120', 'Bonnet Library Endowment/Vern' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30782', '782', '48780', 'Library Acquisition Endowed Fu' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30784', '784', '65640', 'Kaiser Aluminum Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30791', '791', '48410', 'McQuiston Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30796', '796', '49820', 'Green Geophysics/Ida' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30798', '798', '65660', 'Downward Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30801', '801', '65720', 'Barrick Gold Endowed Undergrad' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30806', '806', '40180', 'Pillar Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30808', '808', '42560', 'Ivanhoe Int''l Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30809', '809', '65840', 'Minerals Industry Ed Foundatio' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30814', '814', '65980', 'Monahan Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30817', '817', '65700', 'Baker Hughes Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30819', '819', '65940', 'St. Mary Land & Exp. Schol.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30820', '820', '49650', 'Tenneco Oil Co. Teaching/Facul' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30821', '821', '77230', 'Hancock Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30824', '824', '49270', 'OITAF-NACS Ropeway Center' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30826', '826', '62460', 'Bruce Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30828', '828', '66060', 'Faculty Scholarship/Geology' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30829', '829', '66000', 'Faculty Scholarship/Mineral Ec' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30831', '831', '66040', 'Stockmar Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30833', '833', '27430', 'Hickey Graduate Research/Harol' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30836', '836', '608368', 'Cone Endowed Memorial Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30846', '846', '67420', 'Van Voris Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30848', '848', '66120', 'Harris Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30849', '849', '49140', 'Kroll Book' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30850', '850', '66160', 'Knox Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30851', '851', '12240', 'Brown Medal' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30857', '857', '66250', 'Zarcone Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30859', '859', '66280', 'White Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30860', '860', '6-08604', 'Carlson Endowed Rugby Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30861', '861', '67470', 'Keating Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30867', '867', '66360', 'Faculty Scholarship Geochemist' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30868', '868', '66400', 'Kissinger Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30869', '869', '66420', 'Math Undergraduates Scholarshi' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30872', '872', '', 'Janzen Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30876', '876', '66520', 'Green Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30877', '877', '49745', 'Erickson Lecture Endowed Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30878', '878', '66560', 'Hutchinson Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30885', '885', '608856', 'Mendenhall Geophysics Prize Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30887', '887', '11440', 'Hays Award - CPR/Harrison L.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30889', '889', '608895', 'Tolen Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30890', '890', '66720', 'Faculty Scholarship - Mining' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30896', 'B896', '608968', 'Houston Orediggers Academic Endowed Schl' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30897', '897', '49840', 'Baker Hughes Distinguished Cha' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30898', '898', '49180', 'Pfeil Library/Emil H. & Adolph' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30899', '899', '62820', 'Perriman Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30900', '900', '66070', 'Mann Memorial/Paul Cyrus' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30903', '903', '66760', 'Itten Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30904', '904', '48520', 'Combined Graduate Fellowship E' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30905', '905', '66800', 'Pegasus Gold Undergraduate Sch' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30906', '906', '62860', 'Hersey Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30907', '907', '66840', 'BHP Billiton Indigenous Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30908', 'B908', '609087', 'Hatch Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30909', '909', '36710', 'Kissock Memorial Award/Alan' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30910', '910', '66880', 'Storer & Earlougher Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30912', 'B912', '609124', 'Dr. Charles Falk Cook Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30921', '921', '49860', 'Green Professorship in Geophys' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30925', '925', '66960', 'Nutter Estate Scholarship/Duan' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30927', '927', '67000', 'Lacy Family Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30929', '929', '67040', 'Detmar Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30931', '931', '67080', 'Doerr Jr. Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30932', '932', '67120', 'DeSollar Scholarship/Tenny Coo' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30935', '935', '67160', 'De Laat Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30936', '936', '67200', 'McQuinn Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30938', '938', '67240', 'Porter Endowed Scholarship Fun' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30940', '940', '14460', 'Baxter Prize/Robert A.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30945', '945', '67320', 'Seaver Estate/Viola' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30947', '947', '67360', 'Conway Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30949', '949', '67400', 'Wilson Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30952', '952', '27520', 'Lake Geology Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30953', '953', '', 'Dickinson Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30958', '958', '67520', 'Murray Scholarship Fund/Mathew' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30962', '962', '33660', 'Shiftar Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30964', '964', '27490', 'Burch Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30965', '965', '30780', 'Pickett Memorial Award/George' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30966', '966', '63820', 'Morse Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30969', '969', '15320', 'Erickson Research Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30971', '971', '49880', 'Chevron International Fellowshi' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30973', '973', '33330', 'Procter & Gamble Foreign Area' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30975', '975', '40280', 'Freeport-McMoRan Copper-Ansell Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30977', '977', '49900', 'Jenni Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30988', '988', '63020', 'Ensign-Bickford Company Endowe' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30997', '997', '47470', 'Wunder Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '32352', '', '623528', '' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '32868', '', '16920', '' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '34361', '4361', '37080', 'Materials Research and Travel' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '34625', '4625', '', 'Physics Department Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30397A (B is below)', '397', '49580', 'Boettcher Distinguished Chair/' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30397B', '397', '', 'Boettcher Distinguished Chair/' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30132', '132', '62570', 'Diver Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30238', '238', '27420', 'Bartshe Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30443', '443', '77260', 'Weiszmann Scholarship/Fred and' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30482', 'B482', '604827', 'George B. Lucas Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30494', 'B494', '604948', 'Grimes Family Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30507', 'B507', '605072', 'Schneider Family End. Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30508', 'B508', '605087', 'Sayers Memorial Scholarship Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30513', 'B513', '605134', 'Washington Internship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30537', '537', '63760', 'Class of ''52 Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30698', '698', '62780', 'Abel Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30766', '766', '65580', 'Rollins Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30812', '812', '49690', 'Grandey Curriculum Mini-Grant' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30827', '827', '608274', 'Goetz Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30839', '839', '27870', 'Weber Endowed Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30862', '862', '66320', 'Temple Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30871', '871', '66440', 'McMahan Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30881', '881', '66640', 'Scrivner Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30928', '928', '33320', 'Grandey Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30980', '980', '67600', 'Cohen Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30987', '987', '33400', 'Irelan Family Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30725', '725', '64880', 'Wyoming Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30943', '943', '67280', 'Champion Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30109', '109', '62560', 'Wood Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30297', '297', '63000', 'Collester Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30303', '303', '20720', 'Slater Family Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30333', '333', '63200', 'Ashe and Burwell Memorial Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30478', '478', '27450', 'Pustmueller Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30504', 'B504', '6-05047', 'Nielsen Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30506', 'B506', '605069', 'Klett, Jr. Endowed Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30511', 'B511', '605112', 'Corbetta Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30520', 'B520', '', 'Rau Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30558', '558', '33280', 'Rebekah B. McBride Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30669', '669', '64000', 'Loren Weimer Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30671', '671', '64040', 'Brown Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30736', '736', '65060', 'Haun Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30775', '775', '65600', 'Bashen Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30788', '788', '65680', 'Arkin Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30800', 'B800', '608002', 'Pool Enhancement Fund In Petroleum Eng.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30810', '810', '15340', 'Daniel Undergrad. Chem. Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30815', '815', '65920', 'Stuart Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30830', '830', '67340', 'Brandon Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30832', '832', '36670', 'Abernethy Endowed Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30834', '834', '608341', 'Abernethy Graduate Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30866', '866', '67460', 'Oborne Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30882', '882', '66680', 'Barrett Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30891', '891', '608918', 'Domenico Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30895', '895', '49850', 'Pink Endowment for International Act.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30902', '902', '25620', 'Weimer Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30913', '913', '42600', 'Poettmann Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30956', '956', '67440', 'Anderson Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30970', '970', '67540', 'Bowie Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30841', '841', '77480', 'James Darden Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30963', '963', '47540', 'McBride Honors Endowed Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30803', '803', '65800', 'Class of ''42 Reunion' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30283', '283', '62940', 'Handwerk Memorial Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30296', '296', '62140', 'Wagner Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30445', 'B445', '604452', 'AWRF Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30464', '464', '49290', 'Wood Mining Archive Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30492', 'B492', '604924', 'Soc. Mining Law Antiquarians End. Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30499', 'B499', '604991', 'Matthew Mitchell Mem. Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30722', '722', '49080', 'Davison Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30750', '750', '65290', 'Sister to Sister Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30870', '870', '49170', 'Dempsey End./Spec. Collections' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30875', '875', '49160', 'LeRoy Endowment/L. W.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30901', '901', '36640', 'Hazen Research Metallurgy' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30972', '972', '67560', 'Dempsey Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30510', 'B510', '605101', 'Annandale-James Mem. Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30273', '273', '62840', 'Loomis Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30292', '292', '62920', 'Burger Memorial Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30323', '323', '48460', 'Hui Oi-Chow Funds' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30415', '415', '63400', 'Fogarty Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30451', '451', '49600', 'Fogarty Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30460', '460', '49620', 'Fogarty Professorship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30461', '461', '33500', 'Kafadar Humanities Award' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30486', '486', '63560', 'Labriola Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30515', 'B515', '605152', 'Mooney Scholarship in Geo. & Geological' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30525', '525', '49060', 'Kafadar Library Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30526', '526', '33220', ' Faculty Development Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30527', '527', '63680', 'Joe McNeill Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30528', '528', '49640', 'Hennebach Prof and Prog in Humanities' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30535', '535', '63720', 'Hochscheid Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30561', '561', '63800', 'Ansell Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30660', 'B660', '606603', 'Harvey Scholars Program Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30704', '704', '20800', 'Thorson Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30707', '707', '49830', 'Rowlinson Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30712', '712', '64720', 'Harry L. McNeill Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30714', '0714', '17320', 'Broussard Family Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30719', '719', '48480', 'Daniels Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30729', '729', '65000', 'Blaster Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30733', '733', '65120', 'Thompson Award Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30747', '747', '65280', 'Grewcock Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30748', '748', '40140', 'Subsurface Engineering Support Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30754', '754', '49550', 'Trefny Endowment for Curriculu' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30758', '758', '48500', 'Hui Fellowship Trust' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30760', '760', '65480', 'Renewal Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30768', '768', '31670', 'Fred and Kathleen Hilterman' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30772', '772', '65460', 'Dueser Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30802', '802', '65760', 'Payne Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30805', '805', '77270', 'Shultz Athletic Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30807', '807', '36600', 'Piper Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30811', '811', '65880', 'Miller Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30822', '822', '608227', 'McInerny Athletic Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30823', '823', '65960', 'Egen Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30835', '835', '77210', 'Thompson Creek End. Schlrsp.' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30842', '842', '66080', 'McKee Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30843', '843', '70350', 'Janzen Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30847', '847', '67450', 'DeFilippo Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30852', '852', '67860', 'Beach Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30856', '856', '66240', 'Ward Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30858', '858', '27530', 'McPeek Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30863', '863', '11400', 'Stermole Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30864', '864', '17400', 'Stermole Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30865', '865', '77250', 'Stermole Athletics Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30873', '873', '66480', 'Silver Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30879', '879', '66600', 'Gray Family Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30911', '911', '36660', 'Ansell Endowed Fellowship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30926', '926', '47420', 'Janzen and Berlin Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30937', '937', '77140', 'Howell Athletic Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30955', '955', '62540', 'Wright Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30981', '981', '47530', 'Schulte Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30982', '982', '36680', 'Schmale Family Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30983', '983', '62980', 'James Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30738', '738', '62300', 'Pegis Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30999', '999', '49920', 'Ansell Chair in Metallurgy' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30147', '147', '62600', 'Ireson Family Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30206', '206', '62680', 'Lame Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30300', '300', '48450', 'Wu Graduate Fellowship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30345', '345', '63280', 'Collier Endowment' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30374', '374', '63360', 'Carr Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30479', 'B479', '604794', 'Chesebro'' Athletic Development Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30483', 'B483', '604836', 'Volk Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30484', 'B484', '304848', 'Drake Memorial Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30491', '491', '63640', 'Dickson Memorial Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30493', 'B493', '604936', 'Ferguson Athletic Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30501', 'B501', '605016', 'Buchanan-Kaplan Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30602', '602', '40200', 'Thompson Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30614', '614', '25500', 'Phillips Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30634', '634', '77120', 'Lofgren Memorial Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30649', '649', '27460', 'Childs Fellowship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30676', '676', '64080', 'Rossi Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30721', '721', '42480', 'Chesebro'' Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30743', '743', '77240', 'Excellence in Football Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30745', '745', '65240', 'Blackwell Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30746', '746', '49480', 'Chesebro'' Distinguished Chair' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30752', '752', '42520', 'Gruver Memorial Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30755', '755', '65360', 'Dickson Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30759', '759', '65440', 'Guenther, Jr. Endowed Scholars' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30763', '763', '77180', 'Gardner Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30767', '767', '62260', 'Isaacs Endowment Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30769', '769', '65590', 'McConaty Athletic Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30776', '776', '65740', 'Houston Academic Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30780', '780', '77220', 'Houston Athletic Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30844', '844', '42580', 'Campbell Endowed Chair' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30845', '845', '67430', 'Korell Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30855', '855', '66200', '''39 Football Team Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30874', '874', '62830', 'Grosvenor Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30883', '883', '608833', 'Johns Family Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30886', '886', '6-08862', 'Campbell Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30892', '892', '608926', 'The Chamberlin Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30893', '893', '608931', 'Long Endowed Scholarship Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30914', '914', '66920', 'Gary Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30919', '919', '60200', 'Bradley Family Endowed Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30920', 'B920', '609208', 'Class of ''33 Melville F. Coolbaugh Award' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30923', '923', '25740', 'Bloom Fund' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30957', '957', '67480', 'Provost Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30804', '804', '63780', 'Class of ''54 Endowed' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30534', '534', '29280', 'Kent Graduate Scholarship' ) 
/
INSERT INTO ADVANCE.A_TEMP_TBK ( A_TEMP_TBK.FUND, A_TEMP_TBK.ACA, A_TEMP_TBK.BANNER, A_TEMP_TBK.FUND_NAME ) 
		 VALUES ( '30730', '730', '65040', 'Christie Canadian Scholarship' ) 
/

commit;

alter table a_temp_tbk add account varchar2(77);
commit;

update a_temp_tbk  t1
set t1.account =
    (select a.account
        from allocation   a
     where a.short_name = t1.fund_name
       and status_code = 'A')
where t1.fund NOT IN
('30707',
'30864',
'30826',
'30811',
'30697',
'30863')
commit;

select * from a_temp_tbk
where account is null
and fund_name is not null;

update a_temp_tbk
set account = '6-3-0864'
where fund = '30864'

alter table a_temp_tbk add alloc varchar2(4);
commit;

update a_temp_tbk  t
set t.alloc =
    (select a.allocation_code from allocation a where t.account = a.account);
commit;

alter table a_temp_tbk add account_stewarded varchar2(1);
commit;

update a_temp_tbk
set account_stewarded = 'Y'
where alloc IN
(select allocation from a_stew_main_9);

update a_temp_tbk
set account_stewarded = 'N'
where alloc NOT IN
(select allocation from a_stew_main_9);

update a_temp_tbk
set account_stewarded = 'U'
where alloc IS NULL;
commit;