truncate table a_temp_hold_ids;
/

INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437713' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10061368' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10250262' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10266260' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311558' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10506320' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437733' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10280733' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404348' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437734' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436185' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411176' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10497753' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313036' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434068' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413722' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435228' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10429302' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10288052' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10294979' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303326' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434455' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313481' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10409109' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10472946' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436615' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440344' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437102' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10230404' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10302902' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437682' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436034' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441388' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303609' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303293' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402300' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433000' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10288527' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406878' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437772' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10496171' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10415055' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10469738' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313939' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10296397' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10060622' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434284' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10442177' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436841' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440016' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413397' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435034' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10059756' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312740' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411103' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412548' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313148' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10421462' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414499' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439315' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434316' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10309899' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10429352' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435205' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10468715' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444251' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10427105' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441425' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10274380' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10309315' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10424991' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410468' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10468389' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441398' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435760' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410028' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10438555' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10419321' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436322' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10309324' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10309424' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433322' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311911' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413391' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439887' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439315' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414860' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312531' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411744' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10429965' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10080560' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10268918' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10310281' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436184' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410028' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440908' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441410' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10429782' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10298010' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10442866' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10291269' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436095' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434203' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10438561' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435590' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10423816' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414161' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10270724' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10274852' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10294237' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404371' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10468931' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436942' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434584' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10429682' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313124' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10289518' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10290511' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10471796' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434587' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10079776' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10310172' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10307792' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412089' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414521' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10300928' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10302934' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10071910' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437432' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10230669' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10416790' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10472651' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434674' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10292485' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404688' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414693' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10273377' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10438260' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10503501' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414848' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10296111' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406869' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436423' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407332' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435362' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412421' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435655' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312653' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312781' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436883' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435883' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10309110' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414524' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10061439' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437283' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437266' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436876' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303574' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412457' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413085' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434304' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440374' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10283550' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10469859' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436789' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439008' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435539' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407400' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433547' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437807' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406399' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10422583' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412115' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434642' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10506552' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437390' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434682' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312515' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10497033' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413544' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313960' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311762' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10422919' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10298010' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10275989' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10292502' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10227886' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403647' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10280310' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436897' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436981' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10425755' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410449' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410406' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437592' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411369' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437263' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308732' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435091' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10471407' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414293' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436442' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433661' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437513' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436322' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10070428' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10068645' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10080498' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402509' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10268918' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10470521' ) 
/
--
-- TABLE INSERT STATEMENTS
--
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440639' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10314883' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407349' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434868' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10408816' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437463' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403377' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436768' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402621' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407381' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313646' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10292724' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433310' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440775' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434286' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413475' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287050' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10470037' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10291175' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403080' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10292743' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10292748' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437764' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436623' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440770' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437861' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436624' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441481' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412581' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439839' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406335' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10315539' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402378' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311926' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411280' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436615' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308976' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434288' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444529' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287536' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287536' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10408785' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435655' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406877' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444533' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440708' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287537' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402740' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437157' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10426615' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404491' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10272471' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10004931' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313727' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311944' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403558' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10468619' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10309424' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435057' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414428' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10292973' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10421846' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308988' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406404' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10063387' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402854' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10098609' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10274241' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404650' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413518' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10297254' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10276603' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412433' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10304789' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10302285' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436627' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10423929' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10298563' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410118' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434292' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10291534' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403200' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412434' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433573' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436847' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10290548' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435706' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403003' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10070428' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435802' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434014' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10079860' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413513' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434236' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437093' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444564' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410303' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410303' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403104' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414964' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414499' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433652' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439508' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10427396' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410392' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10270619' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10230404' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10293398' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10096047' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436074' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434299' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414813' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10408090' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10283728' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439887' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414524' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10024971' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10290330' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404540' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402676' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10283229' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436163' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435534' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436416' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10290315' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10279622' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433854' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10422144' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303825' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403212' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439828' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10097496' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407466' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403570' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311524' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312647' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413927' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10230818' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10298996' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10306863' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413510' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10288651' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311986' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412452' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439874' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410463' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308974' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10468768' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411545' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10281649' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10029286' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10422207' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411309' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414501' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436784' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308208' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414530' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412457' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407327' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10472537' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10251026' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413722' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402148' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435108' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433371' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311695' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402485' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412784' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413191' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10059756' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10297957' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439514' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406891' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413521' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437680' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402266' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403967' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412565' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435748' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404240' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404552' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10293841' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407475' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287659' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413524' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10310702' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10279870' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441884' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10293902' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10469929' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311813' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410599' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10274380' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437258' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404216' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441497' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308203' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10270930' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10284985' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439757' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10275539' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10471197' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10047698' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437200' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436336' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10469859' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10408368' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437393' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10299344' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439008' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303132' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10281816' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414710' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10301644' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10068645' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10061448' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10428543' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441199' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10428546' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436229' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404015' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412464' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434838' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412124' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437765' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436077' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404649' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407348' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313621' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413719' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10310590' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406372' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436375' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407483' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10084829' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10428727' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10309809' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435475' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402544' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10294237' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413381' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312036' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404371' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444620' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10428826' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440297' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433323' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10250262' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312740' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303990' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10500714' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10281955' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436848' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410117' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436034' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311738' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402987' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439713' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440645' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10470074' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410506' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434892' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10424817' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10299650' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410433' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440034' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434319' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434617' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10275994' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10314191' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10302154' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10294477' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410510' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10429191' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435228' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10288305' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414536' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437152' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410151' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403865' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403408' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10429302' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411103' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10100414' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412789' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437391' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10292403' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10469814' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411332' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10429352' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10416855' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433554' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441410' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437048' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10470565' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406368' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437390' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10468675' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312546' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439600' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10284077' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403588' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313944' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404688' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10438559' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433887' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436166' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407329' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303609' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435044' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437938' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10292336' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437057' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10282150' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10290326' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10497033' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403063' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414963' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10304996' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287485' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10285654' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402349' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10408087' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10288052' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414806' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433385' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411557' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10002256' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435863' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10471796' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403754' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10408093' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10285708' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10056352' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287068' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10290142' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407330' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437901' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10294979' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10307932' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287218' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10314353' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312697' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312697' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435417' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10430129' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402638' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10282267' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402150' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10301747' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10276354' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437098' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10297960' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10280004' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435907' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436377' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10301975' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10010385' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402147' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10079776' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413549' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10273377' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10422919' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412496' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407412' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10290912' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436275' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410072' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407500' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403256' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402410' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313148' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444670' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437038' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402961' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402585' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10470841' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434381' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10467896' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10277102' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440404' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10289399' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413558' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10470161' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437099' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414970' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435826' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10430504' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433000' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10274574' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10275996' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435973' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436276' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10279049' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10309301' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10305887' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287595' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10080560' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10430623' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10438621' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403647' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440740' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10307273' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10307277' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10407504' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312122' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410424' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10303336' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436078' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435394' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312127' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10439835' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411360' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403322' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10288527' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433472' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436818' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10251371' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10310792' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440715' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10442866' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444704' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10091431' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410687' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10251424' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444706' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403265' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10295611' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414168' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10305096' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433331' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436240' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10304693' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437509' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410461' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436950' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10291269' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434938' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10425673' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10289367' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403649' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10310281' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10044480' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436821' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414800' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411170' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10431201' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308850' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10444717' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434942' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435205' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312148' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10301639' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313992' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411361' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10273626' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10287564' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10473783' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412089' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413552' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312787' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434673' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10440818' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434799' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10056003' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10307825' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402757' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434504' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10315737' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436578' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436823' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436824' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312283' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410111' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10295942' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10273679' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312927' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435149' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404653' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10251102' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412786' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308713' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404122' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10297266' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404123' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10308716' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433768' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10411181' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414153' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10415052' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403150' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412894' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10302740' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10289662' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10404243' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10468715' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412522' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413554' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10250989' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10415055' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434276' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10405970' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312174' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10297039' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433422' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10304357' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10273758' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434555' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311741' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436049' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10279962' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433320' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10300993' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10289747' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434943' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10312181' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10251807' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402420' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10231573' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10271974' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410174' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10402630' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413092' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435341' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441460' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414497' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10279500' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10290053' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10406931' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437107' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10432064' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10063377' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436435' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403591' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10230881' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437119' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10306592' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437786' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10433786' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10310894' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434815' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10301420' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10291512' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436953' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10296397' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10284206' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434455' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10071910' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10403479' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10432250' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10441990' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10302035' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10437475' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10409128' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410402' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10435014' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10471407' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412546' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10472644' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410171' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10408382' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10415051' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10436908' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10412101' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10413547' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10496640' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313056' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10432483' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10434203' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10313811' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10416603' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10414129' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10410125' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10472568' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10470632' ) 
/
INSERT INTO ADVANCE.A_TEMP_HOLD_IDS ( A_TEMP_HOLD_IDS.ID_NUMBER ) 
		 VALUES ( '10311724' ) 
/
commit;

--select * from a_temp_hold_ids

select count(*)
from a_temp_hold_ids;

select count(distinct(id_number))
from a_temp_hold_ids;

update a_temp_hold_ids t
set t.adv_number =
    (select i.id_number
       from ids  i
    where i.ids_type_code = 'CID'
      and i.other_id = t.id_number);
commit;


/*** Nick Mines Mag UG Graduating Seniors List ***/
/*** NOTE:  Nick gave me a list of all CWID's of people who are graduating in Spring, Field, Summer, or December ***/
/*** NOTE:  We will ONLY be storing the NEXT sememster (in this case, Spring) of graduating seniors in Advance, so if he wants this moving forward, he needs to get the list of CWIDs himself ***/
/*** NOTE:   This can be merged with the list Nick pulls from Advance, BUT the first 2 columns must be reversed ***/
select distinct t.adv_number id_number,
            dw.person_or_org, 
            dw.record_type_desc,
            dw.pref_class_year,
            dw.pref_jnt_mail_name,
            dw.jnt_salutation,
            dw.p_addr_type_code,
            dw.p_company_name_1,
            dw.p_company_name_2,
            dw.p_business_title,
            dw.p_street1,
            dw.p_street2,
            dw.p_street3,
            dw.p_zipcode,
            dw.p_cityline,
            dw.p_foreign_cityzip,
            dw.p_country_desc,
            dw.p_flag_foreign,
            dw.flag_mines_mag,
            dw.pref_name_sort,
            dw.record_type_code,
            dw.p_country_code
from a_temp_hold_ids   t,
        a_dw_address_good  dw
where dw.id_number = t.adv_number
and (dw.p_flag_foreign <> 1 or dw.p_zipcode <> ' ')
and t.adv_number NOT IN
    (select mm.id_number
        from a_mines_magazine mm
      where mm.flag_mines_mag NOT IN (0,3) 
         and mm.p_flag_tanfc = 0
         and (p_flag_foreign = 1 or p_zipcode <> ' '));