select a.id_number, a.pref_mail_name, a.pref_name_sort, 
       a.h_care_of,
         a.h_company_name_1,
         a.h_company_name_2,
         a.h_business_title,
         a.h_street1,
         a.h_street2,
         a.h_street3,
         a.h_city,
         a.h_state_code,
         a.h_state_desc,
         a.h_zipcode,
         a.h_cityline,
         a.h_foreign_cityzip,
         a.h_country_code,
         a.h_country_desc,
         a.h_flag_foreign,
         a.h_email_address,
         a.h_phone_status,
         a.h_phone_area_code,
         a.h_phone_number,
         a.h_phone_extension,
         a.h_phone_formatted,
         a.h_phone_unlisted_ind,
         a.h_fax_formatted,
         a.h_foreign_phone,
         a.h_foreign_fax,
         a.p_addr_type_code,
         a.p_care_of,
         a.p_company_name_1,
         a.p_company_name_2,
         a.p_business_title,
         a.p_street1,
         a.p_street2,
         a.p_street3,
         a.p_city,
         a.p_state_code,
         a.p_state_desc,
         a.p_zipcode,
         a.p_cityline,
         a.p_foreign_cityzip,
         a.p_country_code,
         a.p_country_desc,
         a.p_flag_foreign,
         a.p_email_address,
         a.p_phone_status,
         a.p_phone_area_code,
         a.p_phone_number,
         a.p_phone_extension,
         a.p_phone_formatted,
         a.p_phone_unlisted_ind,
         a.p_fax_formatted,
         a.p_foreign_phone,
         a.p_foreign_fax
from a_dw_address_good      a,
     a_dw_jobs              j
where j.id_number           = a.id_number
  and a.p_zipcode between '77000-0000' and '77799-9999'
  and j. employer_id_number in (
'0000018067','0000018068','0000025665',
'0000029633',
'0000029631',
'0000034526',
'0000024589',
'0000029691',
'0000025663',
'0000032146',
'0000032268',
'0000018323')
   and j.record_status_code = 'A'
	and j.record_type_code   = 'AL'
   and j.job_status_code in ('R','C')