/*** Women alumni report ***/
/*** NOTE:  this is a_alumni_female_alums in Advance/Powerbuilder ***/
select a.id_number, a.pref_mail_name, a.pref_name_sort, a.pref_class_year, d.degrees,
a.p_company_name_1,
a.p_company_name_2,
a.p_business_title,
a.p_street1,
a.p_street2,
a.p_street3,
a.p_city,
a.p_state_code,
a.p_zipcode,
a.p_foreign_cityzip,
a.p_country_code,
a.p_email_address,
a.p_phone_formatted,
a.h_street1,
a.h_street2,
a.h_street3,
a.h_city,
a.h_state_code,
a.h_zipcode,
a.h_foreign_cityzip,
a.h_country_code,
a.h_phone_formatted,
a.b_company_name_1,
a.b_company_name_2,
a.b_business_title,
a.b_street1,
a.b_street2,
a.b_street3,
a.b_city,
a.b_state_code,
a.b_zipcode,
a.b_foreign_cityzip,
a.b_country_code,
a.b_phone_formatted,
a.b_email_address,
DECODE(a.flag_dns,'1','True','False') as do_not_solicit,
DECODE(a.flag_omit_from_mail,'1','True','False') as do_not_mail,
DECODE(a.flag_dnp,'1','True','False') as do_not_phone,
NVL((select 'True' from dual where a.id_number IN (select m.id_number from mailing_list m where m.mail_list_code = 'EXE' and addr_type_code = 'E')),'False') as do_not_email_home,
NVL((select 'True' from dual where a.id_number IN (select m.id_number from mailing_list m where m.mail_list_code = 'EXE' and addr_type_code = 'B')),'False') as do_not_email_business,
NVL((select 'True' from dual where a.id_number IN (select m.id_number from mailing_list m where m.mail_list_code = 'DNI')),'False') as do_not_invite
from a_dw_address_good   a,
        a_dw_degree_count   d
where a.id_number = d.id_number
and a.record_type_code = 'AL'
and a.id_number in
    (select e.id_number from entity e where e.gender_code = 'F');