/*** Anita Pariseau ***/
CREATE USER ADV_APARISEAU IDENTIFIED BY VALUES '31789AE2EF215FD3'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_APARISEAU
/
ALTER USER ADV_APARISEAU DEFAULT ROLE ADVROLE
/

/*** Athletics ***/
CREATE USER ADV_ATHLETICS IDENTIFIED BY VALUES '06ED73580435064A'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_ATHLETICS
/
ALTER USER ADV_ATHLETICS DEFAULT ROLE ADVROLE
/

/*** Becky Leewaye ***/
CREATE USER ADV_BLEEWAYE IDENTIFIED BY VALUES '8B6D2446AF10D4FC'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_BLEEWAYE
/
ALTER USER ADV_BLEEWAYE DEFAULT ROLE ADVROLE
/

/*** Kathy Breit ***/
CREATE USER ADV_BREIT IDENTIFIED BY VALUES '41D31DB3CB952C69'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_BREIT
/
ALTER USER ADV_BREIT DEFAULT ROLE ADVROLE
/

/*** Brian Dowling ***/
CREATE USER ADV_BRIAND IDENTIFIED BY VALUES 'CE0FF17A8C2E4E39'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_BRIAND
/
ALTER USER ADV_BRIAND DEFAULT ROLE ADVROLE
/

/*** Brinton ***/
CREATE USER ADV_BRINTON IDENTIFIED BY VALUES '163CAB8F483F3E5F'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_BRINTON
/
ALTER USER ADV_BRINTON DEFAULT ROLE ADVROLE
/

/*** BSR Support ***/
CREATE USER ADV_BSRSUPPORT IDENTIFIED BY VALUES '728887B7F269785C'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_BSRSUPPORT
/
ALTER USER ADV_BSRSUPPORT DEFAULT ROLE ADVROLE
/

/*** Burris ***/
CREATE USER ADV_BURRIS IDENTIFIED BY VALUES 'F0508D628BEDD381'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_BURRIS
/
ALTER USER ADV_BURRIS DEFAULT ROLE ADVROLE
/

/*** Carol Chapman ***/
CREATE USER ADV_CCHAPMAN IDENTIFIED BY VALUES 'DD77A7F653464216'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_CCHAPMAN
/
ALTER USER ADV_CCHAPMAN DEFAULT ROLE ADVROLE
/

/*** Chris Wenger ***/
CREATE USER ADV_CWENGER IDENTIFIED BY VALUES '8BCE050EA89F46DB'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_CWENGER
/
ALTER USER ADV_CWENGER DEFAULT ROLE ADVROLE
/

/*** Dell Boyd ***/
CREATE USER ADV_DBOYD IDENTIFIED BY VALUES '741A4F7F7BB82ED1'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_DBOYD
/
ALTER USER ADV_DBOYD DEFAULT ROLE ADVROLE
/

/*** ADV Department ***/
CREATE USER ADV_DEPARTMENT IDENTIFIED BY VALUES '426E77BBF7609EFB'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_DEPARTMENT
/
ALTER USER ADV_DEPARTMENT DEFAULT ROLE ADVROLE
/

/*** Karen Shaw-Devlin ***/
CREATE USER ADV_DEVLIN IDENTIFIED BY VALUES 'A6067F58B78C44D3'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_DEVLIN
/
ALTER USER ADV_DEVLIN DEFAULT ROLE ADVROLE
/

/*** David Rein ***/
CREATE USER ADV_DREIN IDENTIFIED BY VALUES 'EFE3B047802A1C18'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_DREIN
/
ALTER USER ADV_DREIN DEFAULT ROLE ADVROLE
/

/*** Diane Scollard ***/
CREATE USER ADV_DSCOLLARD IDENTIFIED BY VALUES 'B146E7C6D3CEE71F'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_DSCOLLARD
/
ALTER USER ADV_DSCOLLARD DEFAULT ROLE ADVROLE
/

/*** Dana Seidle ***/
CREATE USER ADV_DSEIDLE IDENTIFIED BY VALUES '91E621C1EDCEA271'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_DSEIDLE
/
ALTER USER ADV_DSEIDLE DEFAULT ROLE ADVROLE
/

/*** Donna Steele ***/
CREATE USER ADV_DSTEELE IDENTIFIED BY VALUES '1FA7883F9CB58787'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_DSTEELE
/
ALTER USER ADV_DSTEELE DEFAULT ROLE ADVROLE
/

/*** Jan Durlin ***/
CREATE USER ADV_DURLIN IDENTIFIED BY VALUES '7F998554A99D4FF4'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_DURLIN
/
ALTER USER ADV_DURLIN DEFAULT ROLE ADVROLE
/

/*** Louisa Duley ***/
CREATE USER ADV_EDULEY IDENTIFIED BY VALUES '642131EF2C69E61A'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_EDULEY
/
ALTER USER ADV_EDULEY DEFAULT ROLE ADVROLE
/

/*** GVansoes ***/
CREATE USER ADV_GVANSOES IDENTIFIED BY VALUES '42B848AAEC14763F'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_GVANSOES
/
ALTER USER ADV_GVANSOES DEFAULT ROLE ADVROLE
/

/*** Nilmini Hecox ***/
CREATE USER ADV_HECOX IDENTIFIED BY VALUES '98926C616AE0733C'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_HECOX
/
ALTER USER ADV_HECOX DEFAULT ROLE ADVROLE
/

/*** Heidi Cox ***/
CREATE USER ADV_HEIDIC IDENTIFIED BY VALUES 'A5D93A19EB4CF69F'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_HEIDIC
/
ALTER USER ADV_HEIDIC DEFAULT ROLE ADVROLE
/

/*** Heather Kenney ***/
CREATE USER ADV_HKENNEY IDENTIFIED BY VALUES '87F9C2ED1D8C25EA'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_HKENNEY
/
ALTER USER ADV_HKENNEY DEFAULT ROLE ADVROLE
/

/*** Jeannie Jacoboson ***/
CREATE USER ADV_JACOBSON IDENTIFIED BY VALUES 'F0B8BFFC8987DD7C'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_JACOBSON
/
ALTER USER ADV_JACOBSON DEFAULT ROLE ADVROLE
/

/*** Judy Arbuckle ***/
CREATE USER ADV_JARBUCKL IDENTIFIED BY VALUES 'F45ED4EE21A94BDA'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_JARBUCKL
/
ALTER USER ADV_JARBUCKL DEFAULT ROLE ADVROLE
/

/*** Julie Rodriguez-MacCallum ***/
CREATE USER ADV_JCRODRIG IDENTIFIED BY VALUES '9FB0145F13E13BB0'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_JCRODRIG
/
ALTER USER ADV_JCRODRIG DEFAULT ROLE ADVROLE
/

/*** Jan Durlin ***/
CREATE USER ADV_JDURLIN IDENTIFIED BY VALUES '552B931ED6008B41'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_JDURLIN
/
ALTER USER ADV_JDURLIN DEFAULT ROLE ADVROLE
/

/*** Jacob Jansonius ***/
CREATE USER ADV_JJANSONI IDENTIFIED BY VALUES '60BAA5F4F39DD74A'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_JJANSONI
/
ALTER USER ADV_JJANSONI DEFAULT ROLE ADVROLE
/

/*** Jo Marie Reeves ***/
CREATE USER ADV_JMREEVES IDENTIFIED BY VALUES '74B2DE8D0B46CFF8'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_JMREEVES
/
ALTER USER ADV_JMREEVES DEFAULT ROLE ADVROLE
/

/*** Jennifer Ramirez ***/
CREATE USER ADV_JRAMIREZ IDENTIFIED BY VALUES 'F3A29FC3CA57758E'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_JRAMIREZ
/
ALTER USER ADV_JRAMIREZ DEFAULT ROLE ADVROLE
/

/*** Janet Blair ***/
CREATE USER ADV_JTBLAIR IDENTIFIED BY VALUES '7C1E46A36561BBAA'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_JTBLAIR
/
ALTER USER ADV_JTBLAIR DEFAULT ROLE ADVROLE
/

/*** Kathy Breit ***/
CREATE USER ADV_KBREIT IDENTIFIED BY VALUES '67B211D83EB2092D'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_KBREIT
/
ALTER USER ADV_KBREIT DEFAULT ROLE ADVROLE
/

/*** Daniel Keyser ***/
CREATE USER ADV_KEYSER IDENTIFIED BY VALUES 'F38D7DA5E1A6C3BB'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_KEYSER
/
ALTER USER ADV_KEYSER DEFAULT ROLE ADVROLE
/

/*** Kim Keller ***/
CREATE USER ADV_KKELLER IDENTIFIED BY VALUES '1D25D8EE2EED026D'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_KKELLER
/
ALTER USER ADV_KKELLER DEFAULT ROLE ADVROLE
/

/*** Kim Lewis ***/
CREATE USER ADV_KMLEWIS IDENTIFIED BY VALUES '1BC0B7BBDB431E5B'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_KMLEWIS
/
ALTER USER ADV_KMLEWIS DEFAULT ROLE ADVROLE
/

/*** Linda Good Wilson ***/
CREATE USER ADV_LGWILSON IDENTIFIED BY VALUES 'DA62C9DDB62025E0'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_LGWILSON
/
ALTER USER ADV_LGWILSON DEFAULT ROLE ADVROLE
/

/*** Linda Landrum ***/
CREATE USER ADV_LLANDRUM IDENTIFIED BY VALUES '401522CC1D98F678'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_LLANDRUM
/
ALTER USER ADV_LLANDRUM DEFAULT ROLE ADVROLE
/

/*** Laura Mesack ***/
CREATE USER ADV_LMESACK IDENTIFIED BY VALUES '5FAEC0A223FC5E77'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_LMESACK
/
ALTER USER ADV_LMESACK DEFAULT ROLE ADVROLE
/

/*** Bryan Mack ***/
CREATE USER ADV_MACK IDENTIFIED BY VALUES '4641C78650A5C2D6'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MACK
/
ALTER USER ADV_MACK DEFAULT ROLE ADVROLE
/

/*** Michael Watson ***/
CREATE USER ADV_MBWATSON IDENTIFIED BY VALUES 'FFCBB1D4B44720E8'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MBWATSON
/
ALTER USER ADV_MBWATSON DEFAULT ROLE ADVROLE
/

/*** Rod McNeill ***/
CREATE USER ADV_MCNEILL IDENTIFIED BY VALUES 'CE304BC153D26A72'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MCNEILL
/
ALTER USER ADV_MCNEILL DEFAULT ROLE ADVROLE
/

/*** Maureen Silva ***/
CREATE USER ADV_MCSILVA IDENTIFIED BY VALUES 'E838B7739F8C1B80'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MCSILVA
/
ALTER USER ADV_MCSILVA DEFAULT ROLE ADVROLE
/

/*** Marv Kay ***/
CREATE USER ADV_MKAY IDENTIFIED BY VALUES '0E9303BC8CAE939D'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MKAY
/
ALTER USER ADV_MKAY DEFAULT ROLE ADVROLE
/

/*** Maureen Keller ***/
CREATE USER ADV_MKELLER IDENTIFIED BY VALUES 'FD76DB172F4A2373'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MKELLER
/
ALTER USER ADV_MKELLER DEFAULT ROLE ADVROLE
/

/*** Miriam Mohammed ***/
CREATE USER ADV_MMOHAMMED IDENTIFIED BY VALUES '70A293DEC5C62D5D'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MMOHAMMED
/
ALTER USER ADV_MMOHAMMED DEFAULT ROLE ADVROLE
/

/*** MMorris ***/
CREATE USER ADV_MMORRIS IDENTIFIED BY VALUES '468B5B97EC3AC668'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MMORRIS
/
ALTER USER ADV_MMORRIS DEFAULT ROLE ADVROLE
/

/*** Mary Pott ***/
CREATE USER ADV_MPOTT IDENTIFIED BY VALUES '9A6B6D86B9BED08F'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MPOTT
/
ALTER USER ADV_MPOTT DEFAULT ROLE ADVROLE
/

/*** Mary Ann Sherrie ***/
CREATE USER ADV_MSHERRIE IDENTIFIED BY VALUES '0405370B39DB92A1'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_MSHERRIE
/
ALTER USER ADV_MSHERRIE DEFAULT ROLE ADVROLE
/

/*** Nancy Bierbaumer ***/
CREATE USER ADV_NANCYB IDENTIFIED BY VALUES '5A6C2D569C84658E'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_NANCYB
/
ALTER USER ADV_NANCYB DEFAULT ROLE ADVROLE
/

/*** Odell ***/
CREATE USER ADV_ODELL IDENTIFIED BY VALUES 'BE2452405FDCEA78'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_ODELL
/
ALTER USER ADV_ODELL DEFAULT ROLE ADVROLE
/

/*** Lisa Olson ***/
CREATE USER ADV_OLSON IDENTIFIED BY VALUES '15218FAE8C30EB9A'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_OLSON
/
ALTER USER ADV_OLSON DEFAULT ROLE ADVROLE
/

/*** Patricia Bohner ***/
CREATE USER ADV_PBOHNER IDENTIFIED BY VALUES '308EEACF942A1F5C'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_PBOHNER
/
ALTER USER ADV_PBOHNER DEFAULT ROLE ADVROLE
/

/*** Peter Han ***/
CREATE USER ADV_PHAN IDENTIFIED BY VALUES '51B8E59D1FC382AF'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_PHAN
/
ALTER USER ADV_PHAN DEFAULT ROLE ADVROLE
/

/*** Lisa Raehling ***/
CREATE USER ADV_RAEHLING IDENTIFIED BY VALUES '7772CEE70885C406'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_RAEHLING
/
ALTER USER ADV_RAEHLING DEFAULT ROLE ADVROLE
/

/*** Ron Brummett ***/
CREATE USER ADV_RBRUMMETT IDENTIFIED BY VALUES 'CE0C82908BA47209'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_RBRUMMETT
/
ALTER USER ADV_RBRUMMETT DEFAULT ROLE ADVROLE
/

/*** Maggie Roderick ***/
CREATE USER ADV_RODERICK IDENTIFIED BY VALUES '9111E1B042053B92'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_RODERICK
/
ALTER USER ADV_RODERICK DEFAULT ROLE ADVROLE
/

/*** Bob Pearson ***/
CREATE USER ADV_RPEARSON IDENTIFIED BY VALUES '9A69417FBA290617'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_RPEARSON
/
ALTER USER ADV_RPEARSON DEFAULT ROLE ADVROLE
/

/*** Rosie Turner ***/
CREATE USER ADV_RTURNER IDENTIFIED BY VALUES '3F71CDCCBB15C1DC'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_RTURNER
/
ALTER USER ADV_RTURNER DEFAULT ROLE ADVROLE
/

/*** Schmidt ***/
CREATE USER ADV_SCHMIDT IDENTIFIED BY VALUES 'DA4CDC0056D24736'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_SCHMIDT
/
ALTER USER ADV_SCHMIDT DEFAULT ROLE ADVROLE
/

/*** Susan Delahunt ***/
CREATE USER ADV_SDELAHUNT IDENTIFIED BY VALUES 'AF30D24BC07C32F1'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_SDELAHUNT
/
ALTER USER ADV_SDELAHUNT DEFAULT ROLE ADVROLE
/

/*** SGeer ***/
CREATE USER ADV_SGEER IDENTIFIED BY VALUES 'B1B911EBF85E959A'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_SGEER
/
ALTER USER ADV_SGEER DEFAULT ROLE ADVROLE
/

/*** Karen Shaw ***/
CREATE USER ADV_SHAW IDENTIFIED BY VALUES '562895551702DDF5'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_SHAW
/
ALTER USER ADV_SHAW DEFAULT ROLE ADVROLE
/

/*** Nick Sutcliffe ***/
CREATE USER ADV_SUTCLIFFE IDENTIFIED BY VALUES 'BD110A9CB7F35C1A'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_SUTCLIFFE
/
ALTER USER ADV_SUTCLIFFE DEFAULT ROLE ADVROLE
/

/*** Sandy Westgard ***/
CREATE USER ADV_SWESTGARD IDENTIFIED BY VALUES 'AF13F2595F14CBA1'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_SWESTGARD
/
ALTER USER ADV_SWESTGARD DEFAULT ROLE ADVROLE
/

/*** Test Guy ***/
CREATE USER ADV_TESTGUY IDENTIFIED BY VALUES '601C4DC866E1021F'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_TESTGUY
/
ALTER USER ADV_TESTGUY DEFAULT ROLE ADVROLE
/

/*** Traci Lanier ***/
CREATE USER ADV_TLANIER IDENTIFIED BY VALUES '353D9955B0FFDE55'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_TLANIER
/
ALTER USER ADV_TLANIER DEFAULT ROLE ADVROLE
/

/*** Chris Wenger ***/
CREATE USER ADV_WENGER IDENTIFIED BY VALUES '0E8F48D4CA2CE9E6'
    DEFAULT TABLESPACE ADVANCE_DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE ADVANCE
    ACCOUNT UNLOCK
/
GRANT ADVROLE TO ADV_WENGER
/
ALTER USER ADV_WENGER DEFAULT ROLE ADVROLE
/

/*** Brian Dowling System ***/
CREATE USER BRIAND IDENTIFIED BY VALUES '88CB143E0ED762A8'
    DEFAULT TABLESPACE SYSTEM
    TEMPORARY TABLESPACE TEMP
    PROFILE DEFAULT
    ACCOUNT UNLOCK
/
GRANT AQ_ADMINISTRATOR_ROLE TO BRIAND WITH ADMIN OPTION
/
GRANT AQ_USER_ROLE TO BRIAND WITH ADMIN OPTION
/
GRANT "CONNECT" TO BRIAND WITH ADMIN OPTION
/
GRANT DBA TO BRIAND WITH ADMIN OPTION
/
GRANT DELETE_CATALOG_ROLE TO BRIAND WITH ADMIN OPTION
/
GRANT EXECUTE_CATALOG_ROLE TO BRIAND WITH ADMIN OPTION
/
GRANT EXP_FULL_DATABASE TO BRIAND WITH ADMIN OPTION
/
GRANT HS_ADMIN_ROLE TO BRIAND WITH ADMIN OPTION
/
GRANT IMP_FULL_DATABASE TO BRIAND WITH ADMIN OPTION
/
GRANT RECOVERY_CATALOG_OWNER TO BRIAND WITH ADMIN OPTION
/
GRANT "RESOURCE" TO BRIAND WITH ADMIN OPTION
/
GRANT SELECT_CATALOG_ROLE TO BRIAND WITH ADMIN OPTION
/
GRANT SNMPAGENT TO BRIAND WITH ADMIN OPTION
/
ALTER USER BRIAND DEFAULT ROLE AQ_ADMINISTRATOR_ROLE,
                               AQ_USER_ROLE,
                               "CONNECT",
                               DBA,
                               DELETE_CATALOG_ROLE,
                               EXECUTE_CATALOG_ROLE,
                               EXP_FULL_DATABASE,
                               HS_ADMIN_ROLE,
                               IMP_FULL_DATABASE,
                               RECOVERY_CATALOG_OWNER,
                               "RESOURCE",
                               SELECT_CATALOG_ROLE,
                               SNMPAGENT
/
GRANT DELETE ANY TABLE TO BRIAND
/
GRANT EXECUTE ANY TYPE TO BRIAND
/
GRANT INSERT ANY TABLE TO BRIAND
/
GRANT SELECT ANY SEQUENCE TO BRIAND
/
GRANT SELECT ANY TABLE TO BRIAND WITH ADMIN OPTION
/
GRANT UNLIMITED TABLESPACE TO BRIAND WITH ADMIN OPTION
/
GRANT UPDATE ANY TABLE TO BRIAND
/

-- Create DDL for DBSNMP has not been generated because it is a system object
/
GRANT "CONNECT" TO DBSNMP
/
GRANT "RESOURCE" TO DBSNMP
/
GRANT SNMPAGENT TO DBSNMP
/
ALTER USER DBSNMP DEFAULT ROLE "CONNECT",
                               "RESOURCE",
                               SNMPAGENT
/
GRANT CREATE PUBLIC SYNONYM TO DBSNMP
/
GRANT UNLIMITED TABLESPACE TO DBSNMP
/

-- Create DDL for OUTLN has not been generated because it is a system object
/
GRANT "CONNECT" TO OUTLN
/
GRANT "RESOURCE" TO OUTLN
/
ALTER USER OUTLN DEFAULT ROLE "CONNECT",
                              "RESOURCE"
/
GRANT EXECUTE ANY PROCEDURE TO OUTLN
/
GRANT UNLIMITED TABLESPACE TO OUTLN
/
GRANT EXECUTE ON SYS.OUTLN_PKG TO OUTLN
/

-- Create DDL for SYS has not been generated because it is a system object
/
GRANT AQ_ADMINISTRATOR_ROLE TO SYS WITH ADMIN OPTION
/
GRANT AQ_USER_ROLE TO SYS WITH ADMIN OPTION
/
GRANT "CONNECT" TO SYS WITH ADMIN OPTION
/
GRANT DBA TO SYS WITH ADMIN OPTION
/
GRANT DELETE_CATALOG_ROLE TO SYS WITH ADMIN OPTION
/
GRANT EXECUTE_CATALOG_ROLE TO SYS WITH ADMIN OPTION
/
GRANT EXP_FULL_DATABASE TO SYS WITH ADMIN OPTION
/
GRANT HS_ADMIN_ROLE TO SYS WITH ADMIN OPTION
/
GRANT IMP_FULL_DATABASE TO SYS WITH ADMIN OPTION
/
GRANT OEM_MONITOR TO SYS WITH ADMIN OPTION
/
GRANT RECOVERY_CATALOG_OWNER TO SYS WITH ADMIN OPTION
/
GRANT "RESOURCE" TO SYS WITH ADMIN OPTION
/
GRANT SELECT_CATALOG_ROLE TO SYS WITH ADMIN OPTION
/
GRANT SNMPAGENT TO SYS WITH ADMIN OPTION
/
ALTER USER SYS DEFAULT ROLE AQ_ADMINISTRATOR_ROLE,
                            AQ_USER_ROLE,
                            "CONNECT",
                            DBA,
                            DELETE_CATALOG_ROLE,
                            EXECUTE_CATALOG_ROLE,
                            EXP_FULL_DATABASE,
                            HS_ADMIN_ROLE,
                            IMP_FULL_DATABASE,
                            OEM_MONITOR,
                            RECOVERY_CATALOG_OWNER,
                            "RESOURCE",
                            SELECT_CATALOG_ROLE,
                            SNMPAGENT
/
GRANT DELETE ANY TABLE TO SYS
/
GRANT EXECUTE ANY PROCEDURE TO SYS
/
GRANT EXECUTE ANY TYPE TO SYS
/
GRANT INSERT ANY TABLE TO SYS
/
GRANT SELECT ANY SEQUENCE TO SYS
/
GRANT SELECT ANY TABLE TO SYS WITH ADMIN OPTION
/
GRANT UPDATE ANY TABLE TO SYS
/
GRANT SELECT ON SYSTEM.DEF$_AQCALL TO SYS WITH GRANT OPTION
/
GRANT SELECT ON SYSTEM.DEF$_CALLDEST TO SYS WITH GRANT OPTION
/
GRANT SELECT ON SYSTEM.DEF$_DESTINATION TO SYS WITH GRANT OPTION
/
GRANT SELECT ON SYSTEM.DEF$_ERROR TO SYS WITH GRANT OPTION
/
GRANT SELECT ON SYSTEM.DEF$_LOB TO SYS WITH GRANT OPTION
/
GRANT DELETE ON SYSTEM.DEF$_TEMP$LOB TO SYS WITH GRANT OPTION
/
GRANT INSERT ON SYSTEM.DEF$_TEMP$LOB TO SYS WITH GRANT OPTION
/
GRANT SELECT ON SYSTEM.DEF$_TEMP$LOB TO SYS WITH GRANT OPTION
/
GRANT UPDATE ON SYSTEM.DEF$_TEMP$LOB TO SYS WITH GRANT OPTION
/
GRANT SELECT ON SYSTEM.REPCAT$_REPPROP TO SYS WITH GRANT OPTION
/
GRANT SELECT ON SYSTEM.REPCAT$_REPSCHEMA TO SYS WITH GRANT OPTION
/

-- Create DDL for SYSTEM has not been generated because it is a system object
/
GRANT ADVROLE TO SYSTEM WITH ADMIN OPTION
/
GRANT ADVSCHEMA TO SYSTEM WITH ADMIN OPTION
/
GRANT AQ_ADMINISTRATOR_ROLE TO SYSTEM WITH ADMIN OPTION
/
GRANT AQ_USER_ROLE TO SYSTEM WITH ADMIN OPTION
/
GRANT "CONNECT" TO SYSTEM WITH ADMIN OPTION
/
GRANT DBA TO SYSTEM WITH ADMIN OPTION
/
GRANT DELETE_CATALOG_ROLE TO SYSTEM WITH ADMIN OPTION
/
GRANT EXECUTE_CATALOG_ROLE TO SYSTEM WITH ADMIN OPTION
/
GRANT EXP_FULL_DATABASE TO SYSTEM WITH ADMIN OPTION
/
GRANT HS_ADMIN_ROLE TO SYSTEM WITH ADMIN OPTION
/
GRANT IMP_FULL_DATABASE TO SYSTEM WITH ADMIN OPTION
/
GRANT RECOVERY_CATALOG_OWNER TO SYSTEM WITH ADMIN OPTION
/
GRANT "RESOURCE" TO SYSTEM WITH ADMIN OPTION
/
GRANT SELECT_CATALOG_ROLE TO SYSTEM WITH ADMIN OPTION
/
GRANT SNMPAGENT TO SYSTEM WITH ADMIN OPTION
/
ALTER USER SYSTEM DEFAULT ROLE AQ_ADMINISTRATOR_ROLE,
                               AQ_USER_ROLE,
                               "CONNECT",
                               DBA,
                               DELETE_CATALOG_ROLE,
                               EXECUTE_CATALOG_ROLE,
                               EXP_FULL_DATABASE,
                               HS_ADMIN_ROLE,
                               IMP_FULL_DATABASE,
                               RECOVERY_CATALOG_OWNER,
                               "RESOURCE",
                               SELECT_CATALOG_ROLE,
                               SNMPAGENT
/
GRANT ALTER ANY CLUSTER TO SYSTEM
/
GRANT ALTER ANY INDEX TO SYSTEM
/
GRANT ALTER ANY LIBRARY TO SYSTEM
/
GRANT ALTER ANY MATERIALIZED VIEW TO SYSTEM
/
GRANT ALTER ANY PROCEDURE TO SYSTEM
/
GRANT ALTER ANY ROLE TO SYSTEM
/
GRANT ALTER ANY SEQUENCE TO SYSTEM
/
GRANT ALTER ANY TABLE TO SYSTEM
/
GRANT ALTER ANY TYPE TO SYSTEM
/
GRANT ALTER DATABASE TO SYSTEM
/
GRANT ALTER PROFILE TO SYSTEM
/
GRANT ALTER RESOURCE COST TO SYSTEM
/
GRANT ALTER ROLLBACK SEGMENT TO SYSTEM
/
GRANT ALTER SESSION TO SYSTEM
/
GRANT ALTER SYSTEM TO SYSTEM
/
GRANT ALTER TABLESPACE TO SYSTEM
/
GRANT ALTER USER TO SYSTEM
/
GRANT ANALYZE ANY TO SYSTEM
/
GRANT AUDIT ANY TO SYSTEM
/
GRANT AUDIT SYSTEM TO SYSTEM
/
GRANT BACKUP ANY TABLE TO SYSTEM
/
GRANT BECOME USER TO SYSTEM
/
GRANT COMMENT ANY TABLE TO SYSTEM
/
GRANT CREATE ANY CLUSTER TO SYSTEM
/
GRANT CREATE ANY DIRECTORY TO SYSTEM
/
GRANT CREATE ANY INDEX TO SYSTEM
/
GRANT CREATE ANY LIBRARY TO SYSTEM
/
GRANT CREATE ANY MATERIALIZED VIEW TO SYSTEM
/
GRANT CREATE ANY PROCEDURE TO SYSTEM
/
GRANT CREATE ANY SEQUENCE TO SYSTEM
/
GRANT CREATE ANY SYNONYM TO SYSTEM
/
GRANT CREATE ANY TABLE TO SYSTEM
/
GRANT CREATE ANY TRIGGER TO SYSTEM
/
GRANT CREATE ANY TYPE TO SYSTEM
/
GRANT CREATE ANY VIEW TO SYSTEM
/
GRANT CREATE CLUSTER TO SYSTEM
/
GRANT CREATE DATABASE LINK TO SYSTEM
/
GRANT CREATE LIBRARY TO SYSTEM
/
GRANT CREATE MATERIALIZED VIEW TO SYSTEM
/
GRANT CREATE PROCEDURE TO SYSTEM
/
GRANT CREATE PROFILE TO SYSTEM
/
GRANT CREATE PUBLIC DATABASE LINK TO SYSTEM
/
GRANT CREATE PUBLIC SYNONYM TO SYSTEM
/
GRANT CREATE ROLE TO SYSTEM
/
GRANT CREATE ROLLBACK SEGMENT TO SYSTEM
/
GRANT CREATE SEQUENCE TO SYSTEM
/
GRANT CREATE SESSION TO SYSTEM
/
GRANT CREATE SYNONYM TO SYSTEM
/
GRANT CREATE TABLE TO SYSTEM
/
GRANT CREATE TABLESPACE TO SYSTEM
/
GRANT CREATE TRIGGER TO SYSTEM
/
GRANT CREATE TYPE TO SYSTEM
/
GRANT CREATE USER TO SYSTEM
/
GRANT CREATE VIEW TO SYSTEM
/
GRANT DELETE ANY TABLE TO SYSTEM
/
GRANT DROP ANY CLUSTER TO SYSTEM
/
GRANT DROP ANY DIRECTORY TO SYSTEM
/
GRANT DROP ANY INDEX TO SYSTEM
/
GRANT DROP ANY LIBRARY TO SYSTEM
/
GRANT DROP ANY MATERIALIZED VIEW TO SYSTEM
/
GRANT DROP ANY PROCEDURE TO SYSTEM
/
GRANT DROP ANY ROLE TO SYSTEM
/
GRANT DROP ANY SEQUENCE TO SYSTEM
/
GRANT DROP ANY SYNONYM TO SYSTEM
/
GRANT DROP ANY TABLE TO SYSTEM
/
GRANT DROP ANY TRIGGER TO SYSTEM
/
GRANT DROP ANY TYPE TO SYSTEM
/
GRANT DROP ANY VIEW TO SYSTEM
/
GRANT DROP PROFILE TO SYSTEM
/
GRANT DROP PUBLIC DATABASE LINK TO SYSTEM
/
GRANT DROP PUBLIC SYNONYM TO SYSTEM
/
GRANT DROP ROLLBACK SEGMENT TO SYSTEM
/
GRANT DROP TABLESPACE TO SYSTEM
/
GRANT DROP USER TO SYSTEM
/
GRANT EXECUTE ANY LIBRARY TO SYSTEM
/
GRANT EXECUTE ANY PROCEDURE TO SYSTEM
/
GRANT EXECUTE ANY TYPE TO SYSTEM
/
GRANT FORCE ANY TRANSACTION TO SYSTEM
/
GRANT FORCE TRANSACTION TO SYSTEM
/
GRANT GRANT ANY PRIVILEGE TO SYSTEM
/
GRANT GRANT ANY ROLE TO SYSTEM
/
GRANT INSERT ANY TABLE TO SYSTEM
/
GRANT LOCK ANY TABLE TO SYSTEM
/
GRANT MANAGE TABLESPACE TO SYSTEM
/
GRANT RESTRICTED SESSION TO SYSTEM
/
GRANT SELECT ANY SEQUENCE TO SYSTEM
/
GRANT SELECT ANY TABLE TO SYSTEM
/
GRANT UNLIMITED TABLESPACE TO SYSTEM WITH ADMIN OPTION
/
GRANT UPDATE ANY TABLE TO SYSTEM
/
GRANT EXECUTE ON SYS.DBMS_ALERT TO SYSTEM
/
GRANT EXECUTE ON SYS.DBMS_AQ TO SYSTEM WITH GRANT OPTION
/
GRANT EXECUTE ON SYS.DBMS_AQADM TO SYSTEM WITH GRANT OPTION
/
GRANT EXECUTE ON SYS.DBMS_AQ_IMPORT_INTERNAL TO SYSTEM WITH GRANT OPTION
/
GRANT EXECUTE ON SYS.DBMS_DEFER_IMPORT_INTERNAL TO SYSTEM
/
GRANT EXECUTE ON SYS.DBMS_REPCAT TO SYSTEM
/
GRANT EXECUTE ON SYS.DBMS_RULE_EXIMP TO SYSTEM WITH GRANT OPTION
/
GRANT ALTER ON SYS.INCEXP TO SYSTEM
/
GRANT DELETE ON SYS.INCEXP TO SYSTEM
/
GRANT INDEX ON SYS.INCEXP TO SYSTEM
/
GRANT INSERT ON SYS.INCEXP TO SYSTEM
/
GRANT REFERENCES ON SYS.INCEXP TO SYSTEM
/
GRANT SELECT ON SYS.INCEXP TO SYSTEM
/
GRANT UPDATE ON SYS.INCEXP TO SYSTEM
/
GRANT ALTER ON SYS.INCFIL TO SYSTEM
/
GRANT DELETE ON SYS.INCFIL TO SYSTEM
/
GRANT INDEX ON SYS.INCFIL TO SYSTEM
/
GRANT INSERT ON SYS.INCFIL TO SYSTEM
/
GRANT REFERENCES ON SYS.INCFIL TO SYSTEM
/
GRANT SELECT ON SYS.INCFIL TO SYSTEM
/
GRANT UPDATE ON SYS.INCFIL TO SYSTEM
/
GRANT ALTER ON SYS.INCVID TO SYSTEM
/
GRANT DELETE ON SYS.INCVID TO SYSTEM
/
GRANT INDEX ON SYS.INCVID TO SYSTEM
/
GRANT INSERT ON SYS.INCVID TO SYSTEM
/
GRANT REFERENCES ON SYS.INCVID TO SYSTEM
/
GRANT SELECT ON SYS.INCVID TO SYSTEM
/
GRANT UPDATE ON SYS.INCVID TO SYSTEM
/
GRANT EXECUTE ON SYS.SYS_GROUP TO SYSTEM
/